Repository firebase/firebase-js-sdk, pull requests merged in 2018-08, with the labels that each got.

#1075 Fix unsound type signature
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#1076 Remove canUseNetwork state.
  packages/firestore/src/remote/remote_store.ts
Labels: Component-Firestore, needs-triage

#1073 Merge
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1077 Merging the latest merge into the previous merge
  packages/firestore/CHANGELOG.md
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/model/path.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/test/unit/local/eager_garbage_collector.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/remote_document_change_buffer.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1069 Merging Persistent Stream refactor
  packages/firestore/CHANGELOG.md
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/model/path.ts
  packages/firestore/src/remote/datastore.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/test/unit/local/eager_garbage_collector.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/remote_document_change_buffer.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#1078 Merging Master into Multi-Tab
  packages/auth/src/error_auth.js
  packages/auth/src/rpchandler.js
  packages/auth/test/rpchandler_test.js
  packages/firestore/CHANGELOG.md
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/model/path.ts
  packages/firestore/src/remote/datastore.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/unit/local/eager_garbage_collector.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/remote_document_change_buffer.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
  packages/rxfire/docs/storage.md
  packages/rxfire/firestore/collection/index.ts
Labels: needs-triage

#1080 Move isPrimary assert to the spec test runner
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1079 Prep rxfire release
  packages/rxfire/package.json
Labels: needs-triage

#1081 Adding back callback assert
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#1074 Fixes servicerworker/client state syncing
  packages/auth/demo/functions/yarn.lock
  packages/auth/demo/public/web-worker.js
  packages/auth/src/messagechannel/defines.js
  packages/auth/src/messagechannel/postmessager.js
  packages/auth/src/messagechannel/receiver.js
  packages/auth/src/messagechannel/sender.js
  packages/auth/src/storage/indexeddb.js
  packages/auth/src/utils.js
  packages/auth/test/messagechannel/postmessager_test.js
  packages/auth/test/messagechannel/receiver_test.js
  packages/auth/test/messagechannel/sender_test.js
  packages/auth/test/storage/indexeddb_test.js
Labels: Component-Auth

#1082 Enable strict function types
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/persistence_promise.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/platform_node/grpc_connection.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/src/util/misc.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/local/persistence_promise.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/helpers.ts
  packages/firestore/tsconfig.json
Labels: Component-Firestore

#1085 Rxfire build fix
  packages/rxfire/.gitignore
  packages/rxfire/package.json
  packages/rxfire/test/firestore.test.ts
Labels: needs-triage

#1086 Revert "Prep rxfire release"
  packages/rxfire/package.json
Labels: needs-triage

#1087 Enable no-floating-promises lint check and fix / suppress violations.
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/test/integration/api/array_transforms.test.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/unit/core/event_manager.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/util/async_queue.test.ts
  packages/firestore/tslint.json
Labels: Component-Firestore, needs-triage

#1088 Multi-Tab Renames
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1093 Make RxFire public
  packages/rxfire/package.json
Labels: needs-triage

#1098 Using BATCHID_UNKNOWN instead of null
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/util/misc.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1097 Removing/Addressing TODOs
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/src/local/remote_document_cache.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/local/test_query_cache.ts
  packages/firestore/test/unit/local/test_remote_document_cache.ts
  packages/firestore/test/unit/local/test_remote_document_change_buffer.ts
Labels: needs-triage

#1099 Updating the indexeddb_persistence class comment
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#1096 Fixed `get({source: 'cache'})` to return nonexistent documents from cache.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/test/integration/api/get_options.test.ts
Labels: Component-Firestore, Type: Bug, needs-triage

#1100 Use previous message for primary lease error
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
Labels: needs-triage

#1103 Spec Test: Sorting Query events
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1102 Remove mutation data from client state
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/model/collections.ts
  packages/firestore/test/integration/api/get_options.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1107 Drop QueryCache.start()
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/test_query_cache.ts
Labels: needs-triage

#1106 Garbage Collect Mutation Batch Keys
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1109 GRPC Tweaks.
  packages/firestore/src/platform_node/grpc_connection.ts
Labels: Component-Firestore, needs-triage

#1108 Garbage Collect the Remote Document Changelog
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
Labels: needs-triage

#1062 rxfire: added functions to map RTDB changes to values
  packages/rxfire/database/list/index.ts
  packages/rxfire/database/object/index.ts
  packages/rxfire/test/database.test.ts
Labels: needs-triage

#1115 Tweak array-contains test for partial object matches.
  packages/firestore/test/unit/core/query.test.ts
Labels: Component-Firestore, Type: Maintenance

#1114 Using mutable spec runner
  packages/firestore/test/unit/specs/perf_spec.test.ts
Labels: needs-triage

#1118 Update Changelog with Multi-Tab Schema Changes
  packages/firestore/CHANGELOG.md
Labels: needs-triage

#1119 Delete stale client metadata
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#1120 firebase-ios-sdk/1499: Restart streams on any token change.
  packages/firestore/src/api/credentials.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: Component-Firestore, Type: Bug, needs-triage

#1123 Delete leftover zombied client IDs
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#1125 Keep stopping starting
  packages/firestore/src/local/memory_remote_document_cache.ts
Labels: needs-triage

#1122 Update Firestore changelog for token change fix (4ec654d).
  packages/firestore/CHANGELOG.md
Labels: Component-Firestore, needs-triage

#1124 Rxfire docs update and adding the snapshot to the percentage observable
  packages/rxfire/README.md
  packages/rxfire/docs/storage.md
  packages/rxfire/storage/index.ts
Labels: needs-triage

#1127 Only delete zombied entries on commit success
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#1128 Garbage Collect Query State
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1130 Remove unused lastUpdateTime
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1131 Attempt to delete client metadata row
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1133 Offline get() improvements.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/remote/online_state_tracker.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/specs/offline_spec.test.ts
  packages/firestore/test/unit/specs/remote_store_spec.test.ts
Labels: Component-Firestore

#1129 Stop saving persistence layer across spec tests
  packages/firestore/test/unit/specs/describe_spec.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/offline_spec.test.ts
  packages/firestore/test/unit/specs/persistence_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: Component-Firestore

#1140 Support BrowserPlatforms with no window or document
  packages/firestore/src/platform_browser/browser_platform.ts
Labels: needs-triage

#1146 Add Changelog entry for ReactNative fix
  packages/firestore/CHANGELOG.md
Labels: needs-triage

#1141 Various auth fixes
  packages/auth/src/exports_lib.js
  packages/auth/src/messagechannel/defines.js
  packages/auth/src/messagechannel/receiver.js
  packages/auth/src/messagechannel/sender.js
  packages/auth/src/storage/indexeddb.js
  packages/auth/src/utils.js
  packages/auth/test/exports_lib_test.js
  packages/auth/test/messagechannel/sender_test.js
  packages/auth/test/storage/indexeddb_test.js
Labels: Component-Auth

#1148 Change removeMutationBatch to remove a single batch
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
Labels: needs-triage

#1153 Make MaybeDocument an abstract class
  packages/firestore/src/api/database.ts
  packages/firestore/src/model/document.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/test/util/helpers.ts
Labels: Component-Firestore

#1147 Speed up FieldPath validation tests
  packages/firestore/test/integration/api/validation.test.ts
Labels: Component-Firestore

#1150 Adding forEach Helper
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/persistence_promise.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/local/persistence_promise.test.ts
Labels: Component-Firestore

#1149 Schema migration that drops held write acks
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/test/unit/local/encoded_resource_path.test.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/simple_db.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/helpers.ts
Labels: Component-Firestore

#1121 Rewrites Auth indexedDB polling
  packages/auth/src/storage/indexeddb.js
  packages/auth/test/storage/indexeddb_test.js
Labels: Component-Auth

#1160 RxFire: Peer deps versions and Rollup config
  packages/rxfire/package.json
  packages/rxfire/rollup.config.js
Labels: needs-triage

#1159 Enable strictNullChecks
  packages/firestore/src/api/database.ts
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/query.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/remote_document_change_buffer.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/model/transform_operation.ts
  packages/firestore/src/platform_browser/webchannel_connection.ts
  packages/firestore/src/platform_node/grpc_connection.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/src/util/sorted_map.ts
  packages/firestore/test/integration/api/array_transforms.test.ts
  packages/firestore/test/integration/api/batch_writes.test.ts
  packages/firestore/test/integration/api/cursor.test.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/fields.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/server_timestamp.test.ts
  packages/firestore/test/integration/api/smoke.test.ts
  packages/firestore/test/integration/api/transactions.test.ts
  packages/firestore/test/integration/api/type.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/integration/util/internal_helpers.ts
  packages/firestore/test/unit/api/document_change.test.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/persistence_promise.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/simple_db.test.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/model/field_value.test.ts
  packages/firestore/test/unit/remote/remote_event.test.ts
  packages/firestore/test/unit/specs/describe_spec.ts
  packages/firestore/test/unit/specs/perf_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/util/async_queue.test.ts
  packages/firestore/test/unit/util/sorted_map.test.ts
  packages/firestore/test/util/api_helpers.ts
  packages/firestore/test/util/equality_matcher.ts
  packages/firestore/test/util/test_platform.ts
  packages/firestore/tsconfig.json
Labels: Component-Firestore

#1171 `navigator.serviceWorker.ready` rejects in chrome extensions.
  packages/auth/src/error_withcredential.js
  packages/auth/src/utils.js
  packages/auth/test/error_test.js
Labels: Component-Auth, Type: Bug

#1104 Adding Firestore team to code owners
  .github/CODEOWNERS
Labels: needs-triage

#1161 Remove Multi-Tab TODOs
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/specs/describe_spec.ts
Labels: needs-triage

#1162 Keep Query state consistent when primary lease is lost
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/util/obj.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
Labels: needs-triage

#1179 Remove start() from Persistence interface
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1174 Checking for UnknownDocument
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/transaction.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/model/mutation.ts
Labels: Component-Firestore

#1172 Add sequence numbers and sync them
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/listen_sequence.ts
  packages/firestore/src/core/types.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/core/listen_sequence.test.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage
