Repository firebase/firebase-js-sdk, pull requests merged in 2018-03, with the labels that each got.

#534 Database API: Ref from Ref
  packages/database-types/index.d.ts
  packages/database/src/api/Database.ts
  packages/database/test/database.test.ts
Labels: needs-triage

#501 [Multi-Tab] Master Election
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/platform/platform.ts
  packages/firestore/src/platform_browser/browser_platform.ts
  packages/firestore/src/platform_node/node_platform.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/test_garbage_collector.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/local/test_query_cache.ts
  packages/firestore/test/unit/local/test_remote_document_cache.ts
  packages/firestore/test/unit/local/test_remote_document_change_buffer.ts
  packages/firestore/test/unit/specs/describe_spec.ts
  packages/firestore/test/unit/specs/persistence_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#412 Add timeout to OnlineState tracking.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/core/event_manager.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/types.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/remote/online_state_tracker.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/unit/core/event_manager.test.ts
  packages/firestore/test/unit/specs/offline_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/util/async_queue.test.ts
Labels: Component-Firestore, Type: Enhancement

#547 Remove unnecessary lcov-result-merger dep from @firebase/messaging
  packages/messaging/package.json
Labels: needs-triage

#551 Release Fixes
  scripts/release/utils/banner.js
  scripts/release/utils/inquirer.js
Labels: needs-triage

#552 Fixes an issue with staged release version
  scripts/release/utils/inquirer.js
Labels: needs-triage

#554 Remove "google-cloud-resource-prefix" header in favor of "database" url parameter in WebChannel requests.
  packages/firestore/src/platform_browser/webchannel_connection.ts
Labels: Component-Firestore, needs-triage

#563 Fixes #562, Adds usePublicVapidKey to firebase/index.d.ts
  packages/firebase/index.d.ts
Labels: needs-triage

#561 Fix missing DB logs issue
  packages/database/src/core/util/util.ts
Labels: needs-triage

#564 Fix for b/74749605: Cancel pending backoff operations when closing streams.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/remote/backoff.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/test/unit/specs/remote_store_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: Component-Firestore, Type: Bug

#529 Passwordless
  packages/auth-types/index.d.ts
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/src/actioncodeinfo.js
  packages/auth/src/actioncodesettings.js
  packages/auth/src/actioncodeurl.js
  packages/auth/src/auth.js
  packages/auth/src/authcredential.js
  packages/auth/src/exports_auth.js
  packages/auth/src/idp.js
  packages/auth/src/rpchandler.js
  packages/auth/test/actioncodeinfo_test.js
  packages/auth/test/actioncodesettings_test.js
  packages/auth/test/actioncodeurl_test.js
  packages/auth/test/auth_test.js
  packages/auth/test/authcredential_test.js
  packages/auth/test/error_test.js
  packages/auth/test/rpchandler_test.js
  packages/firebase/externs/firebase-auth-externs.js
Labels: needs-triage

#530 Refactor Auth storage test
  packages/auth/demo/public/script.js
  packages/auth/src/authstorage.js
  packages/auth/src/error_auth.js
  packages/auth/src/exports_auth.js
  packages/auth/src/iframeclient/iframewrapper.js
  packages/auth/src/recaptchaverifier/recaptchaverifier.js
  packages/auth/src/rpchandler.js
  packages/auth/src/storage/asyncstorage.js
  packages/auth/src/storage/factory.js
  packages/auth/src/storage/indexeddb.js
  packages/auth/src/storage/inmemorystorage.js
  packages/auth/src/storage/localstorage.js
  packages/auth/src/storage/mockstorage.js
  packages/auth/src/storage/nullstorage.js
  packages/auth/src/storage/sessionstorage.js
  packages/auth/src/storage/storage.js
  packages/auth/src/storageusermanager.js
  packages/auth/src/utils.js
  packages/auth/test/auth_test.js
  packages/auth/test/autheventmanager_test.js
  packages/auth/test/authstorage_test.js
  packages/auth/test/cordovahandler_test.js
  packages/auth/test/recaptchaverifier/recaptchaverifier_test.js
  packages/auth/test/rpchandler_test.js
  packages/auth/test/storage/asyncstorage_test.js
  packages/auth/test/storage/factory_test.js
  packages/auth/test/storage/indexeddb_test.js
  packages/auth/test/storage/inmemorystorage_test.js
  packages/auth/test/storage/localstorage_test.js
  packages/auth/test/storage/mockstorage_test.js
  packages/auth/test/storage/nullstorage_test.js
  packages/auth/test/storage/sessionstorage_test.js
  packages/auth/test/storageautheventmanager_test.js
  packages/auth/test/storageoauthhandlermanager_test.js
  packages/auth/test/storagependingredirectmanager_test.js
  packages/auth/test/storageredirectusermanager_test.js
  packages/auth/test/storageusermanager_test.js
  packages/auth/test/testhelper.js
  packages/auth/test/utils_test.js
Labels: needs-triage

#565 Remove assert I accidentally left in (I meant to remove it when I re-added the defensive check above).
  packages/firestore/CHANGELOG.md
  packages/firestore/src/remote/persistent_stream.ts
Labels: Component-Firestore, Type: Maintenance

#567 Adds Auth tests to demo app for web worker environment functionality.
  packages/auth/demo/public/common.js
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/demo/public/web-worker.js
Labels: Component-Auth, Type: Enhancement, feature-request

#574 Add missing function in Auth interface
  packages/firebase/index.d.ts
Labels: needs-triage

#571 Adds tests in demo app for service worker compatibility with Firebase Auth
  packages/auth/.gitignore
  packages/auth/buildtools/run_demo.sh
  packages/auth/demo/firebase.json
  packages/auth/demo/functions/index.js
  packages/auth/demo/functions/package-lock.json
  packages/auth/demo/functions/package.json
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/demo/public/service-worker.js
  packages/auth/demo/public/web-worker.js
Labels: Component-Auth, Type: Enhancement

#575 added typedef for passwordless and new sign in methods which returns …
  packages/firebase/index.d.ts
Labels: needs-triage

#578 Fetch API missing support handling
  packages/auth/demo/public/script.js
  packages/auth/demo/public/web-worker.js
  packages/auth/package.json
  packages/auth/src/rpchandler.js
  packages/auth/src/utils.js
  packages/auth/test/rpchandler_test.js
  packages/auth/test/utils_test.js
  yarn.lock
Labels: Component-Auth, Type: Bug, Type: Enhancement

#583 added new method declarations
  packages/firebase/app/index.d.ts
Labels: needs-triage

#587 Unify pushSubscription/publicVapidKey retrievals
  packages/messaging/src/controllers/controller-interface.ts
Labels: needs-triage

#586 Adding getActiveClients()
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/test/unit/specs/persistence_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#592 Fix issue that could cause offline get()s to wait up to 10 seconds.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/remote/online_state_tracker.ts
  packages/firestore/test/unit/specs/offline_spec.test.ts
Labels: Component-Firestore, Type: Bug

#596 Updates the @firebase/webchannel-wrapper Version
  packages/webchannel-wrapper/package.json
  yarn.lock
Labels: needs-triage

#584 Persisting mutation batch state in LocalStorage
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
  packages/firestore/src/remote/remote_syncer.ts
  packages/firestore/src/util/misc.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#598 Tweaks message for useServiceWorker error
  packages/messaging/src/models/errors.ts
Labels: needs-triage

#597 Renaming ClientKey to ClientId
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#589 Retrieving the list of active clients after registering the WebStorage handler
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#599 Fix Issue 474
  packages/firebase/index.d.ts
Labels: needs-triage

#604 Paring FDL link in getActionCodeFromSignInEmailLink to support deep link
  packages/auth/src/authcredential.js
  packages/auth/test/auth_test.js
  packages/auth/test/authcredential_test.js
Labels: needs-triage

#600 Update packages/firebase/app/index.d.ts with all the API changes we've made in the last couple months.
  packages/firebase/app/index.d.ts
Labels: needs-triage

#603 Small cleanup to FieldValue sentinel code to make it easier to add more sentinels in the future.
  packages/firestore/src/api/field_value.ts
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/test/integration/api/validation.test.ts
Labels: Component-Firestore, Type: Enhancement, Type: Maintenance

#601 Plumbing through SharedStorageState
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#544 Make Timestamp a part of the public Firestore API.
  packages/firebase/app/index.d.ts
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/CHANGELOG.md
  packages/firestore/index.node.ts
  packages/firestore/index.ts
  packages/firestore/karma.conf.js
  packages/firestore/src/api/database.ts
  packages/firestore/src/api/timestamp.ts
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/core/snapshot_version.ts
  packages/firestore/src/core/timestamp.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/model/field_value.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/model/mutation_batch.ts
  packages/firestore/src/platform/config.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/integration/api/batch_writes.test.ts
  packages/firestore/test/integration/api/cursor.test.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/fields.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/server_timestamp.test.ts
  packages/firestore/test/integration/api/type.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/api/timestamp.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/model/field_value.test.ts
  packages/firestore/test/unit/model/mutation.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
Labels: needs-triage
