Repository firebase/firebase-js-sdk, pull requests merged in 2018-11, with the labels that each got.

#1351 Lockdown the version of yarn to 1.10.1 in our Travis environment.
  .travis.yml
Labels: needs-triage

#1359 [README] Supported Node.js versions for SDK development
  README.md
Labels: needs-triage

#1361 added return type definition to useFunctionsEmulator
  packages/functions-types/index.d.ts
Labels: needs-triage

#1354 Remove Mutation tombstones
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/model/mutation_batch.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
Labels: Component-Firestore

#1353 Upgrade GRPC to 1.16.0
  packages/firestore/package.json
  packages/testing/package.json
  yarn.lock
Labels: needs-triage

#1364 update yarn.lock
  yarn.lock
Labels: needs-triage

#1366 Throw a more helpful error if there isn't a 'sub' field
  packages/testing/src/api/index.ts
  packages/testing/test/database.test.ts
Labels: needs-triage

#1355 Use orphaned docs as part of GC calculation
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/lru_garbage_collector.ts
  packages/firestore/src/local/memory_persistence.ts
Labels: needs-triage

#1378 Fix waitsForCount in EventAccumulator (tests)
  packages/database/test/helpers/EventAccumulator.ts
Labels: needs-triage

#1386 Expose database and firestore namespaces in the @firebase/testing module
  packages/testing/index.ts
Labels: needs-triage

#1390 Limit gRPC's built-in exponential backoff
  packages/firestore/src/platform_node/grpc_connection.ts
Labels: needs-triage

#1375 Upgrade mocha version to 5.2.0 in all packages.
  integration/browserify/package.json
  integration/firestore/package.json
  integration/messaging/package.json
  integration/typescript/package.json
  integration/webpack/package.json
  packages/app/package.json
  packages/database/package.json
  packages/firestore/package.json
  packages/functions/package.json
  packages/logger/package.json
  packages/messaging/package.json
  packages/rxfire/package.json
  packages/template/package.json
  packages/testing/package.json
  packages/util/package.json
  yarn.lock
Labels: needs-triage

#1393 Fix weird prettifier issue
  packages/testing/index.ts
Labels: needs-triage

#1382 Added ability to custom FDL domain
  packages/auth-types/index.d.ts
  packages/auth/src/actioncodesettings.js
  packages/auth/src/error_auth.js
  packages/auth/src/rpchandler.js
  packages/auth/test/actioncodesettings_test.js
  packages/auth/test/auth_test.js
  packages/auth/test/authuser_test.js
  packages/auth/test/rpchandler_test.js
  packages/firebase/index.d.ts
Labels: needs-triage

#1401 Fix error catching for IDBRequest.error.
  packages/auth/src/storage/indexeddb.js
Labels: Component-Auth

#1394 Update grpc to 1.16.1 to support node 11
  packages/firestore/package.json
  packages/testing/package.json
  yarn.lock
Labels: needs-triage

#1405 Rework FieldMask to use a SortedSet of FieldPaths
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
Labels: needs-triage
