Repository firebase/firebase-js-sdk, pull requests merged in 2018-12, with the labels that each got.

#1408 Fix flaky database transaction test.
  packages/database/test/transaction.test.ts
Labels: Component-Database, needs-triage

#1410 Change getFreshRepo() to only take a path, and use the DATABASE_URL constant.
  packages/database/test/helpers/util.ts
  packages/database/test/info.test.ts
Labels: needs-triage

#1343 Saml
  packages/auth-types/index.d.ts
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/src/auth.js
  packages/auth/src/authcredential.js
  packages/auth/src/authevent.js
  packages/auth/src/autheventmanager.js
  packages/auth/src/authuser.js
  packages/auth/src/defines.js
  packages/auth/src/error_auth.js
  packages/auth/src/exports_auth.js
  packages/auth/src/idp.js
  packages/auth/src/rpchandler.js
  packages/auth/test/auth_test.js
  packages/auth/test/authcredential_test.js
  packages/auth/test/authevent_test.js
  packages/auth/test/autheventmanager_test.js
  packages/auth/test/authuser_test.js
  packages/auth/test/error_test.js
  packages/auth/test/idp_test.js
  packages/auth/test/rpchandler_test.js
  packages/firebase/index.d.ts
Labels: needs-triage

#1411 Internal persistence settings
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
Labels: needs-triage

#1392 Wire together LRU garbage collection
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/lru_garbage_collector.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/model/collections.ts
  packages/firestore/src/platform/config.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/local/lru_garbage_collector.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1412 Add LRU changelog entry
  packages/firestore/CHANGELOG.md
Labels: needs-triage

#1414 Enable database test with local emulator.
  .travis.yml
  config/webpack.test.js
  packages/database/src/core/ReadonlyRestClient.ts
  packages/database/test/connection.test.ts
  packages/database/test/database.test.ts
  packages/database/test/helpers/util.ts
  packages/database/test/info.test.ts
  packages/database/test/query.test.ts
  packages/database/test/transaction.test.ts
  scripts/testing/database-emulator-test.js
Labels: needs-triage

#1424 Finish type migration and get rid of AnyDuringMigration
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/util/misc.ts
  packages/firestore/src/util/promise.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1427 Changed email validation logic to allow international email address
  packages/auth/src/rpchandler.js
  packages/auth/src/utils.js
  packages/auth/test/rpchandler_test.js
  packages/auth/test/utils_test.js
Labels: needs-triage

#1435 Add code for managing emulators and running database/firestore emulator tests via yarn commands.
  .travis.yml
  package.json
  packages/firestore/test/integration/util/helpers.ts
  scripts/emulator-testing/database-test-runner.ts
  scripts/emulator-testing/emulators/database-emulator.ts
  scripts/emulator-testing/emulators/emulator.ts
  scripts/emulator-testing/emulators/firestore-emulator.ts
  scripts/emulator-testing/firestore-test-runner.ts
  scripts/emulator-testing/tsconfig.json
  scripts/testing/database-emulator-test.js
Labels: needs-triage

#1433 Port performance optimizations to speed up reading large collections from Android
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/memory_remote_document_cache.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/remote_document_cache.ts
  packages/firestore/src/local/remote_document_change_buffer.ts
  packages/firestore/src/model/collections.ts
  packages/firestore/src/model/document.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/src/util/sorted_set.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/local/test_remote_document_cache.ts
Labels: Component-Firestore

#1441 Fixes #1436: Ensure only the primary tab tries to garbage collect.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/lru_garbage_collector.ts
  packages/firestore/src/remote/remote_store.ts
Labels: Component-Firestore, Type: Bug
