Repository firebase/firebase-js-sdk, pull requests merged in 2018-06, with the labels that each got.

#893 Remove Alec from Messaging owners
  .github/CODEOWNERS
Labels: needs-triage

#894 Update Chrome and Safari version in cross-browser test.
  .browserslistrc
  .travis.yml
  config/karma.saucelabs.js
Labels: needs-triage

#895 Adding @hiranya911 to root owners
  .github/CODEOWNERS
Labels: needs-triage

#892 Test for b/72533250.
  packages/firestore/test/unit/specs/limbo_spec.test.ts
Labels: Component-Firestore, needs-triage

#870 Auth type update
  packages/auth-types/index.d.ts
  packages/firebase/index.d.ts
Labels: needs-triage

#907 Draining on client switches
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#819 Added ES module bundle to the auth package
  packages/auth/buildtools/run_tests.sh
  packages/auth/gulpfile.js
  packages/auth/package.json
Labels: Component-Auth

#915 Removing tsconfig.json from prod build
  packages/firebase/.npmignore
  packages/firebase/package.json
  packages/firestore/src/remote/remote_store.ts
Labels: needs-triage

#903 Refine onSnapshot tests to ensure correct number of events emitted
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/util/events_accumulator.ts
Labels: needs-triage

#942 Add FcmOptions interface and link property
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/interfaces/message-payload.ts
  packages/messaging/test/sw-controller.test.ts
Labels: Component-Messaging

#937 fix(auth): Fixes issue when hybrid indexedDB incorrectly fallsback to localStorage
  packages/auth/src/storage/hybridindexeddb.js
Labels: Component-Auth, Priority: P1, Type: Bug

#929 [Multi-Tab] Adding logging to SharedClientState (small)
  packages/firestore/src/local/shared_client_state.ts
Labels: needs-triage

#924 Add firebase-functions to README.
  packages/firebase/README.md
Labels: needs-triage

#885 Exporting firebase as namespace
  packages/firebase/index.d.ts
Labels: needs-triage

#927 [Multi-Tab] Generating mutation IDs from persistence (medium)
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/util/misc.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
  packages/firestore/test/unit/util/misc.test.ts
Labels: needs-triage

#955 [Multi-Tab] Don't disable network on shutdown
  packages/firestore/src/core/sync_engine.ts
Labels: needs-triage

#959 Workaround for IndexedDb bug
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
Labels: needs-triage

#960 Remove startsWith because it's not supported in IE11
  packages/database/src/core/util/libs/parser.ts
Labels: needs-triage

#961 Add an optional parameter for region to Functions constructor.
  packages/firebase/index.d.ts
  packages/functions/index.ts
Labels: needs-triage

#956 Add a method to allow using Functions with the local emulator.
  packages/functions-types/index.d.ts
  packages/functions/package.json
  packages/functions/src/api/service.ts
  packages/functions/test/callable.test.ts
  packages/functions/test/service.test.ts
Labels: needs-triage

#963 Add onBlocked handler for schema upgrade
  packages/firestore/src/local/simple_db.ts
Labels: needs-triage

#933 WIP: RxFire
  packages/rxfire/.gitignore
  packages/rxfire/auth/index.ts
  packages/rxfire/auth/package.json
  packages/rxfire/firestore/collection/index.ts
  packages/rxfire/firestore/document/index.ts
  packages/rxfire/firestore/fromRef.ts
  packages/rxfire/firestore/index.ts
  packages/rxfire/firestore/package.json
  packages/rxfire/functions/index.ts
  packages/rxfire/functions/package.json
  packages/rxfire/karma.conf.js
  packages/rxfire/package.json
  packages/rxfire/rollup.config.js
  packages/rxfire/storage/index.ts
  packages/rxfire/storage/package.json
  packages/rxfire/test/firestore.test.ts
  packages/rxfire/tsconfig.json
  yarn.lock
Labels: needs-triage

#920 [Multi-Tab] Round-tripping queries (not small)
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/memory_remote_document_cache.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/src/local/remote_document_cache.ts
  packages/firestore/src/local/remote_document_change_buffer.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/remote/remote_event.ts
  packages/firestore/test/unit/core/event_manager.test.ts
  packages/firestore/test/unit/core/view.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/test_remote_document_cache.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/limit_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
  packages/firestore/test/util/helpers.ts
Labels: needs-triage

#926 [Multi-Tab] Propagating online state
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#930 [Multi-Tab] Handling mutations during failover
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#964 Updating list of "Top Level" reviewers
  .github/CODEOWNERS
Labels: needs-triage

#969 Add spec test support for target-scoped resume tokens
  packages/firestore/src/remote/remote_syncer.ts
  packages/firestore/test/unit/specs/existence_filter_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#971 fixed updateCurrentUser test failure on IE11/10
  packages/auth/test/auth_test.js
Labels: needs-triage

#970 [Multi-Tab] Handling user changes
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#973 Clears getRedirectResult() in AuthEventManager for a deleted Auth instance
  packages/auth/src/auth.js
  packages/auth/src/autheventmanager.js
  packages/auth/test/auth_test.js
  packages/auth/test/autheventmanager_test.js
Labels: Component-Auth, Type: Bug

#968 [Multi-Tab] Recomputing views after failover
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage
