Repository firebase/firebase-js-sdk, pull requests merged in 2018-05, with the labels that each got.

#750 updateCurrentUser api
  packages/auth-types/index.d.ts
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/src/args.js
  packages/auth/src/auth.js
  packages/auth/src/authuser.js
  packages/auth/src/error_auth.js
  packages/auth/src/exports_auth.js
  packages/auth/src/token.js
  packages/auth/test/args_test.js
  packages/auth/test/auth_test.js
  packages/auth/test/authuser_test.js
  packages/auth/test/testhelper.js
  packages/auth/test/token_test.js
Labels: needs-triage

#751 fix diff function to do deep comparison
  packages/auth/src/utils.js
  packages/auth/test/utils_test.js
Labels: needs-triage

#754 phone auth testing
  packages/auth-types/index.d.ts
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/src/auth.js
  packages/auth/src/authsettings.js
  packages/auth/src/exports_auth.js
  packages/auth/src/recaptchaverifier/grecaptcha.js
  packages/auth/src/recaptchaverifier/grecaptchamock.js
  packages/auth/src/recaptchaverifier/loader.js
  packages/auth/src/recaptchaverifier/mockloader.js
  packages/auth/src/recaptchaverifier/realloader.js
  packages/auth/src/recaptchaverifier/recaptchaverifier.js
  packages/auth/src/utils.js
  packages/auth/test/auth_test.js
  packages/auth/test/authsettings_test.js
  packages/auth/test/recaptchaverifier/grecaptchamock_test.js
  packages/auth/test/recaptchaverifier/mockloader_test.js
  packages/auth/test/recaptchaverifier/realloader_test.js
  packages/auth/test/recaptchaverifier/recaptchaverifier_test.js
  packages/auth/test/utils_test.js
Labels: Component-Auth

#753 Post-indexeddbshim test fixes
  packages/firestore/package.json
  packages/firestore/test/integration/util/helpers.ts
Labels: Component-Firestore, needs-triage

#756 Wording Fixes
  packages/firebase/src/index.ts
Labels: needs-triage

#724 Added TypeScript definitions for firebase.functions()
  packages/firebase/index.d.ts
Labels: needs-triage

#718 docs(firebase): gcloud -> google-cloud
  packages/firebase/README.md
Labels: needs-triage

#758 updated externs and type def
  packages/firebase/externs/firebase-auth-externs.js
  packages/firebase/index.d.ts
Labels: needs-triage

#760 Don't overwrite user defined data
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/test/sw-controller.test.ts
Labels: Component-Messaging

#762 Fix Edge not setting default transaction mode
  packages/messaging/src/models/db-interface.ts
Labels: needs-triage

#761 Fix up changelog.
  packages/firestore/CHANGELOG.md
Labels: Component-Firestore

#717 Disable httpHeadersOverwriteParam for ReactNative to address #703.
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/platform_browser/webchannel_connection.ts
Labels: Component-Firestore

#765 b/78539022: Fix test at risk of range violation errors depending on time-of-day.
  packages/firestore/test/integration/api/cursor.test.ts
Labels: Component-Firestore, needs-triage

#766 Speed up spec tests with connection backoffs
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#700 Check browser support before instantiating controllers
  integration/shared/validator.js
  packages/functions/test/browser/callable.test.ts
  packages/messaging/index.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/index.test.ts
  packages/messaging/test/window-controller.test.ts
Labels: Component-Messaging

#772 IE11 "Can't redefine non-configurable property 'length'" Error
  packages/firestore/src/api/database.ts
Labels: needs-triage

#773 Enable Messaging tests on Sauce Labs
  config/karma.saucelabs.js
  packages/messaging/index.ts
  packages/messaging/package.json
  packages/messaging/test/constructor.test.ts
  packages/messaging/test/controller-delete-token.test.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/controller-interface.test.ts
  packages/messaging/test/db-interface.test.ts
  packages/messaging/test/get-sw-reg.test.ts
  packages/messaging/test/helpers.test.ts
  packages/messaging/test/iid-model.test.ts
  packages/messaging/test/index.test.ts
  packages/messaging/test/sw-controller.test.ts
  packages/messaging/test/testing-utils/make-fake-subscription.ts
  packages/messaging/test/testing-utils/make-fake-sw-reg.ts
  packages/messaging/test/testing-utils/messaging-test-runner.ts
  packages/messaging/test/token-details-model.test.ts
  packages/messaging/test/vapid-details-model.test.ts
  packages/messaging/test/window-controller.test.ts
  yarn.lock
Labels: Component-Messaging

#763 Add arrayUnion() and arrayRemove() Transforms (not publicly exposed yet)
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/src/api/field_value.ts
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/model/transform_operation.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/integration/api/array_transforms.test.ts
  packages/firestore/test/integration/api/server_timestamp.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/util/events_accumulator.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/model/mutation.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
  packages/firestore/test/util/helpers.ts
Labels: Component-Firestore, needs-triage

#783 fixed wrong return type in auth-extern
  packages/firebase/externs/firebase-auth-externs.js
Labels: needs-triage

#775 Allow passing in .rules or .rulesPath
  packages/testing/src/api/index.ts
  packages/testing/test/database.test.ts
Labels: needs-triage

#769 Add types for messaging.isSupported()
  packages/firebase/index.d.ts
Labels: Component-Core, Component-Messaging

#764 Array Contains support (not publicly exposed yet).
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/query.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/core/query.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
Labels: Component-Firestore, needs-triage

#770 Combine Observer and PartialObserver types
  packages/app-types/private.d.ts
  packages/messaging-types/index.d.ts
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/util/src/subscribe.ts
  packages/util/test/subscribe.test.ts
Labels: Component-Core, Component-Messaging

#781 Test cleanup: Create indexeddbshim SQLite files in a temporary directory now that https://github.com/axemclion/IndexedDBShim/issues/319 is fixed.
  packages/firestore/.gitignore
  packages/firestore/package.json
  packages/firestore/test/util/node_persistence.ts
  yarn.lock
Labels: Component-Firestore, Type: Maintenance, needs-triage

#788 Fixed Generic type Observer
  packages/auth-types/index.d.ts
  packages/storage-types/index.d.ts
Labels: needs-triage

#786 Update Observer and Messaging types to match internal types
  packages/firebase/index.d.ts
  packages/firestore/test/util/node_persistence.ts
  packages/messaging-types/index.d.ts
  packages/messaging/src/controllers/controller-interface.ts
Labels: needs-triage

#789 Add tests for *-types packages
  packages/app-types/package.json
  packages/app-types/tsconfig.json
  packages/auth-types/package.json
  packages/auth-types/tsconfig.json
  packages/database-types/package.json
  packages/database-types/tsconfig.json
  packages/firestore-types/package.json
  packages/firestore-types/tsconfig.json
  packages/functions-types/package.json
  packages/functions-types/tsconfig.json
  packages/messaging-types/package.json
  packages/messaging-types/tsconfig.json
  packages/storage-types/package.json
  packages/storage-types/tsconfig.json
  packages/template-types/package.json
  packages/template-types/tsconfig.json
Labels: needs-triage

#794 Refresh token instead of breaking if VAPID key doesn't exist
  packages/messaging/src/controllers/controller-interface.ts
Labels: Component-Messaging

#730 Refactoring Messaging
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/test/window-controller.test.ts
Labels: Component-Messaging

#796 SubImport Typings Fix
  packages/firebase/.gitignore
  packages/firebase/tsconfig.json
Labels: needs-triage

#802 Fix variable and class names
  packages/messaging/index.ts
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/models/clean-v1-undefined.ts
  packages/messaging/src/models/db-interface.ts
  packages/messaging/src/models/iid-model.ts
  packages/messaging/src/models/token-details-model.ts
  packages/messaging/src/models/vapid-details-model.ts
  packages/messaging/test/constructor.test.ts
  packages/messaging/test/controller-delete-token.test.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/controller-interface.test.ts
  packages/messaging/test/db-interface.test.ts
  packages/messaging/test/get-sw-reg.test.ts
  packages/messaging/test/iid-model.test.ts
  packages/messaging/test/index.test.ts
  packages/messaging/test/sw-controller.test.ts
  packages/messaging/test/token-details-model.test.ts
Labels: Component-Messaging

#803 Update Firestore Changelog
  packages/firestore/CHANGELOG.md
Labels: needs-triage

#805 Multiple Issue Fixes
  integration/firebase-typings/index.submodules.ts
  integration/firebase-typings/index.ts
  packages/app/index.node.ts
  packages/app/index.rn.ts
  packages/app/package.json
  packages/app/rollup.config.js
  packages/firebase/.gitignore
  packages/firebase/app/package.json
  packages/firebase/auth/package.json
  packages/firebase/database/package.json
  packages/firebase/firestore/package.json
  packages/firebase/functions/package.json
  packages/firebase/messaging/package.json
  packages/firebase/package.json
  packages/firebase/rollup.config.js
  packages/firebase/src/index.ts
  packages/firebase/storage/package.json
  packages/firebase/tsconfig.json
Labels: needs-triage

#810 Update messaging CODEOWNERS
  .github/CODEOWNERS
Labels: needs-triage

#785 Update grpc to 1.11.3
  packages/firestore/package.json
  yarn.lock
Labels: Component-Core, Component-Firestore

#822 Remove part of the mergeField comment
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
Labels: needs-triage

#823 Treating onabort as an error
  packages/firestore/package.json
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/test/unit/local/simple_db.test.ts
  scripts/release/cli.js
  yarn.lock
Labels: needs-triage

#825 Mikelehen/doc changes for each
  packages/firestore/src/api/database.ts
Labels: Component-Firestore, needs-triage

#827 allow storing Object.create(null) in documents
  packages/firestore/src/util/input_validation.ts
Labels: needs-triage

#833 Prettier Code Styling for isPlainObject
  packages/firestore/src/util/input_validation.ts
Labels: needs-triage

#832 Update import statements in documentation
  packages/firebase/README.md
Labels: Component-Core

#821 Enable IE11 testing on SauceLabs.
  .browserslistrc
  config/karma.saucelabs.js
  integration/browserify/package.json
  integration/typescript/package.json
  integration/webpack/package.json
  packages/functions/src/serializer.ts
  packages/polyfill/index.ts
  packages/util/src/errors.ts
  yarn.lock
Labels: needs-triage

#835 b/79432277: Limit Queries to only a single array-contains clause.
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/query.ts
  packages/firestore/test/integration/api/validation.test.ts
Labels: Component-Firestore, needs-triage

#836 Add pkg.browser to firebase/app
  packages/firebase/app/package.json
Labels: needs-triage

#837 Remove test-only error logs
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#842 DOC: Add a link to the release notes in README.md
  README.md
Labels: needs-triage

#840 Update rtdb types
  packages/database-types/index.d.ts
Labels: needs-triage

#846 Falling back on ABORTED_ERROR
  packages/database-types/index.d.ts
  packages/firestore/src/core/firestore_client.ts
Labels: needs-triage

#845 Propagating RTDB type changes
  packages/database/src/api/DataSnapshot.ts
  packages/database/src/core/snap/ChildrenNode.ts
  packages/firebase/index.d.ts
Labels: needs-triage

#844 Adding Firestore to README/Cleaning up Externs
  packages/firebase/README.md
  packages/firebase/externs/firebase-app-externs.js
  packages/firebase/externs/firebase-app-internal-externs.js
  packages/firebase/externs/firebase-auth-externs.js
  packages/firebase/externs/firebase-client-auth-externs.js
  packages/firebase/externs/firebase-database-externs.js
  packages/firebase/externs/firebase-error-externs.js
  packages/firebase/externs/firebase-firestore-externs.js
  packages/firebase/externs/firebase-messaging-externs.js
  packages/firebase/externs/firebase-storage-externs.js
Labels: needs-triage

#847 Explain when to use @firebase/firestore
  packages/firestore/README.md
Labels: needs-triage

#854 Adding ability to run prettier for Firestore
  packages/firestore/package.json
Labels: needs-triage

#856 Add missing tslib dependency
  packages/functions/package.json
Labels: needs-triage

#838 Generating target IDs from persistence
  packages/firestore/src/core/target_id_generator.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/core/target_id_generator.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/test_query_cache.ts
  packages/firestore/test/unit/specs/spec_builder.ts
Labels: needs-triage

#851 Reworking PersistencePromise.waitFor to not use chaining
  packages/firestore/src/local/persistence_promise.ts
  packages/firestore/test/unit/local/simple_db.test.ts
Labels: needs-triage

#862 Use isArrayBufferEqual to compare VAPID keys
  packages/messaging/src/models/iid-model.ts
  packages/messaging/test/iid-model.test.ts
Labels: Component-Messaging

#863 Make @firebase/messaging a module with exports
  packages/firebase/messaging/index.ts
  packages/functions/test/browser/callable.test.ts
  packages/messaging-types/index.d.ts
  packages/messaging/index.ts
  packages/messaging/package.json
  packages/messaging/src/controllers/base-controller.ts
  packages/messaging/test/index.test.ts
Labels: needs-triage

#864 Improves "Could not reach Firestore backend." log message.
  packages/firestore/src/remote/online_state_tracker.ts
  packages/firestore/src/remote/remote_store.ts
Labels: Component-Firestore, needs-triage

#869 Moving getStore() to SimpleDb
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/simple_db.ts
Labels: needs-triage

#782 Storing a Query Changelog
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_remote_document_cache.ts
  packages/firestore/src/local/remote_document_cache.ts
  packages/firestore/src/local/remote_document_change_buffer.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/remote_document_change_buffer.test.ts
  packages/firestore/test/unit/local/test_remote_document_cache.ts
  packages/firestore/test/util/helpers.ts
Labels: Component-Firestore

#877 Allow field deletes for SetOptions.mergeFields
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/test/integration/api/database.test.ts
Labels: needs-triage

#886 Check if cookies are enabled
  packages/messaging/index.ts
Labels: needs-triage

#891 Addressing comments for https://github.com/firebase/firebase-js-sdk/pull/877
  packages/firestore/test/integration/api/database.test.ts
Labels: needs-triage
