Repository firebase/firebase-js-sdk, pull requests merged in 2018-07, with the labels that each got.

#972 Refactor pendingWrites / write pipeline.
  packages/firestore/src/remote/remote_store.ts
Labels: needs-triage

#976 [Multi-Tab] Rename WebStorage key for Multi-Tab
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#940 Force refresh token if RPC fails with "Unauthenticated" error
  packages/firestore/src/api/credentials.ts
  packages/firestore/src/remote/datastore.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/rpc_error.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/integration/util/internal_helpers.ts
Labels: Component-Firestore, needs-triage

#996 Add @davideast as a CODEOWNER - [ci skip]
  .github/CODEOWNERS
Labels: needs-triage

#992 [Multi-Tab] Using fixed client IDs in spec tests
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: Component-Firestore

#979 Embed metadata directly into the RPC call
  packages/firestore/src/platform_node/grpc_connection.ts
Labels: needs-triage

#993 [Multi-Tab] Making Platform, Window and Document Mock available in all tests
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/test_platform.ts
Labels: Component-Firestore

#990 [Multi-Tab] Supporting non-initial initial queries
  packages/firestore/src/core/event_manager.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/core/view_snapshot.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
Labels: needs-triage

#1001 Added missing types for optional database instance.
  packages/firebase/index.d.ts
Labels: needs-triage

#999 [Multi-Tab] Solving startup race
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#995 [Multi-Tab] Remove `withGcEnabled` for tests that don't call `unlisten`
  packages/firestore/test/unit/specs/listen_spec.test.ts
Labels: needs-triage

#980 [Multi-Tab] Making Multi-Tab optional
  packages/firestore-types/index.d.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1004 Expose array transforms and array contains queries.
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/field_value.ts
  packages/firestore/test/integration/api/array_transforms.test.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/model/mutation.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
Labels: needs-triage

#988 Move fieldFilter (free function) to Filter.create()
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/query.ts
  packages/firestore/test/util/helpers.ts
Labels: needs-triage

#1007 Enable firestore sdk to talk to emulator
  packages/testing/index.ts
  packages/testing/package.json
  packages/testing/src/api/index.ts
  packages/testing/test/database.test.ts
Labels: needs-triage

#1010 Setting GarbageSource in SyncEngine's constructor
  packages/firestore/src/core/sync_engine.ts
Labels: needs-triage

#1011 Removing no longer applicable comment
  packages/firestore/src/local/local_store.ts
Labels: needs-triage

#1017 Modify spec test to demonstrate deletedDoc issue.
  packages/firestore/test/unit/specs/listen_spec.test.ts
Labels: needs-triage

#1014 b/72533250: Fix issue with limbo resolutions triggering incorrect manufactured deletes.
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
Labels: Component-Firestore, Type: Bug

#1015 Allow remote updates from watch to heal a cache with synthesized deletes in it
  packages/firestore/src/local/local_store.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
Labels: Component-Firestore, Type: Bug

#1020 Fix method name in comment.
  packages/firestore/src/core/sync_engine.ts
Labels: Component-Auth, Component-Core, needs-triage

#1021 Rename synchronizeTabs to experimentalTabSynchronization
  packages/firestore-types/index.d.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: needs-triage

#994 [Multi-Tab] Tying primary lease to network state
  packages/firestore/src/core/event_manager.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/types.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/core/event_manager.test.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/limit_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/persistence_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1023 Making sure we don't export 'experimental'
  packages/firestore/test/unit/specs/describe_spec.ts
Labels: needs-triage

#1013 [Multi-Tab] Zombie all client data
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/test/util/test_platform.ts
Labels: needs-triage

#1019 Add a schema migration that drops the query cache
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
Labels: Component-Firestore, needs-triage

#1024 Add a release note for the fix to #1548
  packages/firestore/CHANGELOG.md
Labels: Component-Firestore, needs-triage

#1029 Ensure that we create an empty TargetGlobal row.
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
Labels: Component-Firestore, Type: Bug, needs-triage

#1027 Unify local.QueryData with the other platforms
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/query_data.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/remote/remote_event.test.ts
Labels: needs-triage

#1022 Add iat to fake access token payload
  packages/testing/src/api/index.ts
  packages/testing/test/database.test.ts
Labels: needs-triage

#1034 [Multi-Tab] Using WebStorage Mock with all IndexedDB tests
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/util/node_persistence.ts
  packages/firestore/test/util/test_platform.ts
Labels: needs-triage

#1037 catch server error RESET_PASSWORD_EXCEED_LIMIT
  packages/auth/src/rpchandler.js
  packages/auth/test/rpchandler_test.js
Labels: needs-triage

#1028 Use Alex's suggested phrasing instead
  packages/firestore/CHANGELOG.md
Labels: Component-Firestore

#1039 Comment out multi-tab flag
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/src/api/database.ts
Labels: needs-triage

#1038 Merging Master into Multi-Tab
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
Labels: needs-triage

#1042 Upgrade GRPC to 1.13.1
  packages/firestore/package.json
  yarn.lock
Labels: needs-triage

#982 (rxfire): unwrap operator
  packages/rxfire/firestore/collection/index.ts
  packages/rxfire/firestore/document/index.ts
  packages/rxfire/test/firestore.test.ts
Labels: needs-triage

#984 [Multi-Tab] Recover from unexpected primary lease loss
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/util/obj.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#1049 [Multi-Tab] Sort the initial set of changes
  packages/firestore/src/core/view_snapshot.ts
  packages/firestore/test/unit/specs/orderby_spec.test.ts
Labels: needs-triage

#1051 [Multi-Tab] Don't add change log entry when there are no changes
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
Labels: needs-triage

#1057 Merging "benchmark spec tests (#1048)"
  packages/firestore/test/unit/specs/describe_spec.ts
  packages/firestore/test/unit/specs/perf_spec.test.ts
Labels: needs-triage

#1056 [Multi-Tab] Don't write document change log when multi-tab is disabled
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
Labels: needs-triage

#1058 Firestore: in tests, silence the verbose warning about old timestamp behavior
  packages/firestore/test/integration/api/fields.test.ts
  packages/firestore/test/util/api_helpers.ts
Labels: Component-Firestore

#1065 Don't look up TargetId in notifyLocalViewChanges
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/local_view_changes.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/util/helpers.ts
Labels: needs-triage

#1059 Add Watch update perf test
  packages/firestore/test/unit/specs/perf_spec.test.ts
Labels: needs-triage

#1064 Catch invalid provider id error
  packages/auth/src/error_auth.js
  packages/auth/src/rpchandler.js
  packages/auth/test/rpchandler_test.js
Labels: needs-triage

#1063 Don't update query target metadata for updates
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/test_query_cache.ts
Labels: needs-triage

#1066 RxFire: Api Change and documentation
  packages/rxfire/docs/storage.md
  packages/rxfire/firestore/collection/index.ts
Labels: needs-triage

#1041 Refactor PersistentStream.
  packages/firestore/src/remote/datastore.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: Component-Firestore, Type: Maintenance

#1052 Implement global resume token
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
Labels: Component-Firestore

#1071 Add a CHANGELOG entry for #1052
  packages/firestore/CHANGELOG.md
Labels: Component-Firestore, needs-triage

#1068 Rename idleTimer and fix comments.
  packages/firestore/src/remote/persistent_stream.ts
Labels: Component-Firestore, needs-triage
