Repository firebase/firebase-js-sdk, pull requests merged in 2018-04, with the labels that each got.

#610 Fix implicit global variable
  packages/polyfill/src/polyfills/promise.ts
Labels: needs-triage

#615 Adding .skip and .only for validation tests
  packages/firestore/test/integration/api/validation.test.ts
  packages/polyfill/src/polyfills/promise.ts
Labels: needs-triage

#622 Refactor default exports into named exports
  packages/messaging/index.ts
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/src/helpers/array-buffer-to-base64.ts
  packages/messaging/src/helpers/base64-to-array-buffer.ts
  packages/messaging/src/models/clean-v1-undefined.ts
  packages/messaging/src/models/db-interface.ts
  packages/messaging/src/models/default-sw.ts
  packages/messaging/src/models/errors.ts
  packages/messaging/src/models/fcm-details.ts
  packages/messaging/src/models/iid-model.ts
  packages/messaging/src/models/notification-permission.ts
  packages/messaging/src/models/token-details-model.ts
  packages/messaging/src/models/vapid-details-model.ts
  packages/messaging/src/models/worker-page-message.ts
  packages/messaging/test/array-buffer-to-base64.test.ts
  packages/messaging/test/constructor.test.ts
  packages/messaging/test/controller-delete-token.test.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/controller-interface.test.ts
  packages/messaging/test/deletedb.test.ts
  packages/messaging/test/get-sw-reg.test.ts
  packages/messaging/test/iid-model-delete-token.test.ts
  packages/messaging/test/iid-model-get-token.test.ts
  packages/messaging/test/iid-model-update-token.test.ts
  packages/messaging/test/make-fake-app.ts
  packages/messaging/test/make-fake-subscription.ts
  packages/messaging/test/make-fake-sw-reg.ts
  packages/messaging/test/sw-controller.test.ts
  packages/messaging/test/testing-utils/db-helper.ts
  packages/messaging/test/testing-utils/detail-comparator.ts
  packages/messaging/test/testing-utils/mock-fetch.ts
  packages/messaging/test/tokenDetailsModel-deleteToken.test.ts
  packages/messaging/test/tokenDetailsModel-getToken.test.ts
  packages/messaging/test/tokenDetailsModel-saveToken.test.ts
  packages/messaging/test/vapid-details-model-delete.test.ts
  packages/messaging/test/vapid-details-model-get.test.ts
  packages/messaging/test/vapid-details-model-save.test.ts
  packages/messaging/test/window-controller.test.ts
Labels: needs-triage

#623 Fixes getToken in SW
  packages/messaging/src/helpers/array-buffer-to-base64.ts
Labels: needs-triage

#629 Add --strict flag to TSConfig and fix errors
  integration/messaging/test/static/app.js
  packages/messaging/index.ts
  packages/messaging/package.json
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/src/models/db-interface.ts
  packages/messaging/src/models/default-sw.ts
  packages/messaging/src/models/errors.ts
  packages/messaging/src/models/fcm-details.ts
  packages/messaging/src/models/iid-model.ts
  packages/messaging/src/models/notification-permission.ts
  packages/messaging/src/models/token-details-model.ts
  packages/messaging/src/models/vapid-details-model.ts
  packages/messaging/src/models/worker-page-message.ts
  packages/messaging/test/controller-delete-token.test.ts
  packages/messaging/test/tokenDetailsModel-deleteToken.test.ts
  packages/messaging/test/tokenDetailsModel-getToken.test.ts
  packages/messaging/test/tokenDetailsModel-saveToken.test.ts
  packages/messaging/tsconfig.json
Labels: needs-triage

#626 IID Model types
  packages/messaging/src/models/iid-model.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/iid-model-delete-token.test.ts
  packages/messaging/test/iid-model-get-token.test.ts
  packages/messaging/test/iid-model-update-token.test.ts
  packages/messaging/test/make-fake-sw-reg.ts
  packages/messaging/test/sw-controller.test.ts
  packages/messaging/test/tokenDetailsModel-getToken.test.ts
Labels: needs-triage

#625 automaticDataCollectionEnabled Flag
  packages/app-types/index.d.ts
  packages/app/src/firebaseApp.ts
  packages/app/test/firebaseApp.test.ts
Labels: needs-triage

#639 Fixing "Type could be null" errors
  packages/messaging/src/models/iid-model.ts
Labels: needs-triage

#637 Add types
  packages/messaging/index.ts
  packages/messaging/package.json
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/src/helpers/array-buffer-to-base64.ts
  packages/messaging/src/helpers/base64-to-array-buffer.ts
  packages/messaging/src/interfaces/token-details.ts
  packages/messaging/src/models/db-interface.ts
  packages/messaging/src/models/iid-model.ts
  packages/messaging/src/models/token-details-model.ts
  packages/messaging/src/models/vapid-details-model.ts
  packages/messaging/src/models/worker-page-message.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/controller-interface.test.ts
  packages/messaging/test/make-fake-app.ts
  packages/messaging/test/sw-controller.test.ts
  packages/messaging/test/testing-utils/detail-comparator.ts
  packages/messaging/test/testing-utils/mock-fetch.ts
  packages/messaging/test/window-controller.test.ts
Labels: needs-triage

#642 Specify types of observer and next function for UploadTask.on
  packages/storage-types/index.d.ts
Labels: needs-triage

#643 Re-enable --strict flag in messaging/
  packages/app/src/firebaseApp.ts
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/src/models/iid-model.ts
  packages/messaging/src/models/token-details-model.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/test/make-fake-sw-reg.ts
  packages/messaging/test/testing-utils/detail-comparator.ts
  packages/messaging/test/tokenDetailsModel-getToken.test.ts
  packages/messaging/tsconfig.json
Labels: needs-triage

#652 Revert "Removing .path from Database Typings"
  packages/database-types/index.d.ts
  packages/firebase/app/index.d.ts
Labels: needs-triage

#654 v5 Change: Removing .path from Database Typings
  packages/database-types/index.d.ts
  packages/firebase/app/index.d.ts
Labels: needs-triage

#655 Indexeddb fix
  packages/auth/src/iframeclient/iframewrapper.js
  packages/auth/src/recaptchaverifier/recaptchaverifier.js
  packages/auth/src/rpchandler.js
  packages/auth/src/storage/asyncstorage.js
  packages/auth/src/storage/factory.js
  packages/auth/src/storage/hybridindexeddb.js
  packages/auth/src/storage/indexeddb.js
  packages/auth/src/storage/inmemorystorage.js
  packages/auth/src/storage/localstorage.js
  packages/auth/src/storage/mockstorage.js
  packages/auth/src/storage/nullstorage.js
  packages/auth/src/storage/sessionstorage.js
  packages/auth/src/utils.js
  packages/auth/test/authstorage_test.js
  packages/auth/test/iframeclient/iframewrapper_test.js
  packages/auth/test/recaptchaverifier/recaptchaverifier_test.js
  packages/auth/test/rpchandler_test.js
  packages/auth/test/storage/factory_test.js
  packages/auth/test/storage/hybridindexeddb_test.js
  packages/auth/test/storage/indexeddb_test.js
  packages/auth/test/utils_test.js
Labels: needs-triage

#657 Update Auth codeowners
  .github/CODEOWNERS
Labels: Component-Auth

#661 Replace "any" types
  packages/messaging/src/models/iid-model.ts
Labels: needs-triage

#651 Deprecate downloadURL property in Storage metadata types.
  packages/firebase/app/index.d.ts
  packages/firebase/index.d.ts
  packages/storage-types/index.d.ts
Labels: needs-triage

#616 Round-tripping pending mutations
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/src/local/remote_document_cache.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#664 Enable TSLint Return Type Check
  packages/firestore/src/api/blob.ts
  packages/firestore/src/api/credentials.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/core/query.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/transaction.ts
  packages/firestore/src/core/view_snapshot.ts
  packages/firestore/src/local/encoded_resource_path.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/model/collections.ts
  packages/firestore/src/model/field_value.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/model/mutation_batch.ts
  packages/firestore/src/model/path.ts
  packages/firestore/src/platform_browser/webchannel_connection.ts
  packages/firestore/src/remote/existence_filter.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/remote_event.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/src/remote/watch_change.ts
  packages/firestore/src/util/api.ts
  packages/firestore/src/util/assert.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/src/util/input_validation.ts
  packages/firestore/src/util/obj.ts
  packages/firestore/src/util/sorted_map.ts
  packages/firestore/test/util/api_helpers.ts
  packages/firestore/test/util/equality_matcher.ts
  packages/firestore/test/util/helpers.ts
  packages/firestore/tslint.json
Labels: needs-triage

#665 TSLINT: Adding No-Console rule
  packages/firestore/tslint.json
Labels: needs-triage

#663 Remove redundant lib declarations
  config/tsconfig.base.json
Labels: needs-triage

#660 Async/await refactor and test fixes
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/test/controller-delete-token.test.ts
  packages/messaging/test/deletedb.test.ts
  packages/messaging/test/get-sw-reg.test.ts
  packages/messaging/test/iid-model-delete-token.test.ts
  packages/messaging/test/iid-model-get-token.test.ts
  packages/messaging/test/iid-model-update-token.test.ts
  packages/messaging/test/iid-model.test.ts
  packages/messaging/test/sw-controller.test.ts
  packages/messaging/test/testing-utils/mock-fetch.ts
Labels: needs-triage

#671 Use core-js for polyfills
  packages/polyfill/index.ts
  packages/polyfill/package.json
  packages/polyfill/src/polyfills/fetch.ts
  packages/polyfill/src/polyfills/global.ts
  packages/polyfill/src/polyfills/promise.ts
  packages/polyfill/src/shims/Array.ts
  packages/polyfill/src/shims/String.ts
  yarn.lock
Labels: needs-triage

#672 Enable noUnusedLocals in TS compiler options
  packages/messaging/src/controllers/controller-interface.ts
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/src/models/db-interface.ts
  packages/messaging/src/models/iid-model.ts
  packages/messaging/src/models/token-details-model.ts
  packages/messaging/test/controller-get-token.test.ts
  packages/messaging/tsconfig.json
Labels: needs-triage

#667 Enabling TSLint for our test cases
  packages/firestore/package.json
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/fields.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/server_timestamp.test.ts
  packages/firestore/test/integration/api/transactions.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/integration/util/events_accumulator.ts
  packages/firestore/test/integration/util/firebase_export.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/integration/util/internal_helpers.ts
  packages/firestore/test/unit/api/database.test.ts
  packages/firestore/test/unit/api/document_change.test.ts
  packages/firestore/test/unit/api/field_path.test.ts
  packages/firestore/test/unit/api/field_value.test.ts
  packages/firestore/test/unit/core/query.test.ts
  packages/firestore/test/unit/local/encoded_resource_path.test.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/reference_set.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/simple_db.test.ts
  packages/firestore/test/unit/local/test_query_cache.ts
  packages/firestore/test/unit/model/field_value.test.ts
  packages/firestore/test/unit/model/mutation.test.ts
  packages/firestore/test/unit/model/path.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
  packages/firestore/test/unit/remote/remote_event.test.ts
  packages/firestore/test/unit/specs/collection_spec.test.ts
  packages/firestore/test/unit/specs/describe_spec.ts
  packages/firestore/test/unit/specs/existence_filter_spec.test.ts
  packages/firestore/test/unit/specs/limbo_spec.test.ts
  packages/firestore/test/unit/specs/limit_spec.test.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/offline_spec.test.ts
  packages/firestore/test/unit/specs/orderby_spec.test.ts
  packages/firestore/test/unit/specs/persistence_spec.test.ts
  packages/firestore/test/unit/specs/remote_store_spec.test.ts
  packages/firestore/test/unit/specs/resume_token_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
  packages/firestore/test/unit/util/api.test.ts
  packages/firestore/test/unit/util/sorted_map.test.ts
  packages/firestore/test/unit/util/sorted_set.test.ts
  packages/firestore/tslint.json
Labels: needs-triage

#676 Upgrade dependencies
  .yarnrc
  config/functions/package.json
  integration/browserify/package.json
  integration/firebase-typings/package.json
  integration/firestore/package.json
  integration/messaging/package.json
  integration/typescript/package.json
  integration/webpack/package.json
  package.json
  packages/app/package.json
  packages/auth/demo/functions/package.json
  packages/auth/package.json
  packages/database/package.json
  packages/firebase/package.json
  packages/firestore/package.json
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
  packages/functions/package.json
  packages/logger/package.json
  packages/messaging/package.json
  packages/polyfill/package.json
  packages/storage/package.json
  packages/template/package.json
  packages/testing/package.json
  packages/util/package.json
  packages/webchannel-wrapper/package.json
  tools/config.js
  yarn.lock
Labels: needs-triage

#673 Add types for Service Worker Controller
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/src/controllers/sw-types.ts
  packages/messaging/src/controllers/window-controller.ts
  packages/messaging/src/models/worker-page-message.ts
  packages/messaging/test/sw-controller.test.ts
Labels: Component-Messaging

#463 GetOptions for controlling offline behaviour
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/get_options.test.ts
  packages/firestore/test/integration/util/helpers.ts
Labels: needs-triage

#677 Minor additional UserDataConverter cleanup.
  packages/firestore/src/api/user_data_converter.ts
Labels: Component-Firestore, needs-triage

#674 Expand browsers support
  .travis.yml
  config/karma.saucelabs.js
  integration/browserify/karma.conf.js
  integration/browserify/package.json
  integration/firestore/karma.conf.js
  integration/firestore/package.json
  integration/typescript/karma.conf.js
  integration/typescript/package.json
  integration/webpack/karma.conf.js
  integration/webpack/package.json
  package.json
  packages/app/karma.conf.js
  packages/app/package.json
  packages/database/karma.conf.js
  packages/database/package.json
  packages/firestore/karma.conf.js
  packages/firestore/package.json
  packages/functions/karma.conf.js
  packages/functions/package.json
  packages/logger/karma.conf.js
  packages/logger/package.json
  packages/messaging/karma.conf.js
  packages/messaging/package.json
  packages/storage/karma.conf.js
  packages/storage/package.json
  packages/template/karma.conf.js
  packages/template/package.json
  packages/util/karma.conf.js
  packages/util/package.json
  yarn.lock
Labels: needs-triage

#680 Saucelabs Badges/Attribution
  README.md
Labels: needs-triage

#682 Fix deployment procedures.
  .travis.yml
Labels: needs-triage

#632 Multi-Tab support for acknowledged batches
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/types.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/persistence_spec.test.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#681 expose custom claims
  packages/auth-types/index.d.ts
  packages/auth/demo/public/index.html
  packages/auth/demo/public/script.js
  packages/auth/src/authuser.js
  packages/auth/src/exports_auth.js
  packages/auth/src/idtoken.js
  packages/auth/src/idtokenresult.js
  packages/auth/test/authuser_test.js
  packages/auth/test/idtoken_test.js
  packages/auth/test/idtokenresult_test.js
  packages/auth/test/testhelper.js
  packages/firebase/index.d.ts
  packages/firestore/src/api/user_data_converter.ts
Labels: needs-triage

#685 Skip deployment for non-release build.
  .travis.yml
Labels: needs-triage

#686 Firestore Node.js External Fix
  packages/firestore/rollup.config.js
Labels: needs-triage

#695 Add pkg.files entry to each package.json
  packages/app/package.json
  packages/auth/package.json
  packages/database/package.json
  packages/firestore/package.json
  packages/functions/package.json
  packages/logger/package.json
  packages/messaging/package.json
  packages/polyfill/package.json
  packages/storage/package.json
  packages/template/package.json
  packages/testing/package.json
  packages/util/package.json
  packages/webchannel-wrapper/package.json
Labels: needs-triage

#694 Update grpc to version 1.10.1
  packages/firestore/package.json
  packages/firestore/test/unit/remote/node/serializer.test.ts
  yarn.lock
Labels: Component-Firestore

#712 Firestore Proto Loading Fix
  packages/firestore/package.json
  packages/firestore/rollup.config.js
  packages/firestore/src/platform_node/load_protos.ts
  yarn.lock
Labels: needs-triage

#713 Update protos
  packages/firestore/src/protos/firestore_proto_api.d.ts
  packages/firestore/src/protos/google/api/http.proto
  packages/firestore/src/protos/google/firestore/v1beta1/common.proto
  packages/firestore/src/protos/google/firestore/v1beta1/document.proto
  packages/firestore/src/protos/google/firestore/v1beta1/firestore.proto
  packages/firestore/src/protos/google/firestore/v1beta1/query.proto
  packages/firestore/src/protos/google/firestore/v1beta1/write.proto
  packages/firestore/src/protos/google/protobuf/any.proto
  packages/firestore/src/protos/google/protobuf/timestamp.proto
Labels: Component-Firestore, needs-triage

#706 Persisting mutation keys in memory
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/mutation_queue.ts
Labels: needs-triage

#707 Adding multi-client support for rejected mutations
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#690 Fix data message not being handled on foreground when backgroundMessageHandler isn't set
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/test/sw-controller.test.ts
Labels: Component-Messaging

#702 Do nothing for action clicks
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/test/sw-controller.test.ts
Labels: Component-Messaging

#721 Update base64-to-array-buffer.ts
  packages/messaging/src/helpers/base64-to-array-buffer.ts
Labels: Component-Messaging

#725 Ban xit and xdescribe (and suppress existing violations).
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/smoke.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
  packages/firestore/test/unit/util/sorted_map.test.ts
  packages/firestore/tslint.json
Labels: Component-Firestore, Type: Maintenance

#728 Use correct assert() method so we get good error messages.
  packages/firestore/test/util/equality_matcher.ts
Labels: Component-Firestore, Type: Maintenance, needs-triage

#696 Options cleanup for includeMetadataChanges
  packages/firestore-types/index.d.ts
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/event_manager.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/core/view_snapshot.ts
  packages/firestore/test/integration/api/batch_writes.test.ts
  packages/firestore/test/integration/api/get_options.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/api/document_change.test.ts
  packages/firestore/test/unit/core/event_manager.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/api_helpers.ts
Labels: needs-triage

#732 Using an IndexedDB mock for Node testing
  packages/firestore/.idea/runConfigurations/All_Tests.xml
  packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml
  packages/firestore/.npmignore
  packages/firestore/package.json
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/test/integration/browser/webchannel.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/local/encoded_resource_path.test.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/remote_document_change_buffer.test.ts
  packages/firestore/test/unit/local/simple_db.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/mock_persistence.ts
  yarn.lock
Labels: needs-triage

#735 Add VS Code launcher for persistence tests and minor cleanup.
  .vscode/launch.json
  packages/firestore/.gitignore
  packages/firestore/package.json
  packages/firestore/test/util/mock_persistence.ts
  yarn.lock
Labels: needs-triage

#731 Add a warning for notifications with too many actions
  packages/messaging/src/controllers/sw-controller.ts
  packages/messaging/test/sw-controller.test.ts
Labels: Component-Messaging

#743 Adding a word to Firestore API doc
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
Labels: needs-triage

#746 Renaming mock_persistence to node_persistence
  .vscode/launch.json
  packages/firestore/.idea/runConfigurations/All_Tests.xml
  packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml
  packages/firestore/test/util/node_persistence.ts
Labels: needs-triage

#736 Manual merge of Persistence Mock
  .vscode/launch.json
  packages/firestore/.idea/runConfigurations/All_Tests.xml
  packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/platform_node/node_platform.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/node_persistence.ts
Labels: needs-triage

#747 Merging Master + Mock Persistence into multi-tab
  .vscode/launch.json
  packages/firestore/.gitignore
  packages/firestore/.idea/runConfigurations/All_Tests.xml
  packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml
  packages/firestore/.npmignore
  packages/firestore/package.json
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/src/platform_node/node_platform.ts
  packages/firestore/test/integration/browser/webchannel.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/local/encoded_resource_path.test.ts
  packages/firestore/test/unit/local/indexeddb_schema.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/remote_document_change_buffer.test.ts
  packages/firestore/test/unit/local/simple_db.test.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/node_persistence.ts
  yarn.lock
Labels: needs-triage

#748 deprecation for I/O
  packages/auth-types/index.d.ts
  packages/auth/src/auth.js
  packages/auth/src/authuser.js
  packages/auth/src/deprecation.js
  packages/auth/src/exports_auth.js
  packages/auth/test/auth_test.js
  packages/auth/test/authuser_test.js
Labels: needs-triage
