Repository firebase/firebase-js-sdk, pull requests merged in 2018-09, with the labels that each got.

#1185 Gracefully handle duplication modified/removed events in rxfire
  packages/rxfire/firestore/collection/index.ts
Labels: needs-triage

#1193 Rename UnknownDocument.readTime to version
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_serializer.ts
Labels: needs-triage

#1196 Comment cleanup
  packages/firestore/src/model/mutation.ts
Labels: Component-Firestore

#1135 Remove Held Write Acks
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/event_manager.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/transaction.ts
  packages/firestore/src/core/view.ts
  packages/firestore/src/core/view_snapshot.ts
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/mutation_queue.ts
  packages/firestore/src/model/document.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/integration/api/batch_writes.test.ts
  packages/firestore/test/integration/api/query.test.ts
  packages/firestore/test/integration/api/server_timestamp.test.ts
  packages/firestore/test/integration/util/events_accumulator.ts
  packages/firestore/test/unit/api/database.test.ts
  packages/firestore/test/unit/core/event_manager.test.ts
  packages/firestore/test/unit/local/local_store.test.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/specs/listen_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
  packages/firestore/test/util/api_helpers.ts
  packages/firestore/test/util/helpers.ts
Labels: Component-Firestore

#1197 Offline get() improvements.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/remote/online_state_tracker.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/unit/specs/offline_spec.test.ts
  packages/firestore/test/unit/specs/remote_store_spec.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/rxfire/firestore/collection/index.ts
Labels: Component-Firestore, Type: Bug, needs-triage

#1200 Rename LocalStorage to WebStorage
  packages/firestore/src/local/shared_client_state.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Labels: needs-triage

#1192 Package.json has bad types reference
  packages/firebase/package.json
Labels: needs-triage

#1194 Add sequence number to QueryData
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/local_serializer.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/src/local/query_data.ts
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/test/unit/local/query_cache.test.ts
  packages/firestore/test/unit/local/test_query_cache.ts
  packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/helpers.ts
Labels: needs-triage

#1203 Adding readwrite-primary mode
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/test/unit/local/remote_document_cache.test.ts
  packages/firestore/test/unit/local/test_garbage_collector.ts
  packages/firestore/test/unit/local/test_mutation_queue.ts
  packages/firestore/test/unit/local/test_query_cache.ts
  packages/firestore/test/unit/local/test_remote_document_cache.ts
  packages/firestore/test/unit/local/test_remote_document_change_buffer.ts
Labels: needs-triage

#1198 Update CHANGELOG.md
  packages/firestore/CHANGELOG.md
Labels: Component-Firestore

#1202 Don't drop empty objects during merge
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/test/integration/api/database.test.ts
Labels: Component-Firestore, needs-triage

#1209 Remove TODO about making SortedSet.size O(1)
  packages/firestore/src/core/view.ts
Labels: needs-triage

#1201 Remove TODOs
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/shared_client_state_syncer.ts
Labels: needs-triage

#1210 b/112778345: Improve argument validation for get().
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/database.ts
  packages/firestore/test/integration/api/validation.test.ts
Labels: Component-Firestore, Type: Maintenance, needs-triage

#1211 b/111221684: Improve error message when passing empty strings to API methods.
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/database.ts
  packages/firestore/src/util/input_validation.ts
  packages/firestore/test/integration/api/validation.test.ts
Labels: Component-Firestore, needs-triage

#1199 Expose multi-tab flag
  packages/firestore-types/index.d.ts
  packages/firestore/CHANGELOG.md
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_remote_document_cache.ts
  packages/firestore/src/local/local_store.ts
  packages/firestore/test/unit/local/indexeddb_persistence.test.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
Labels: needs-triage

#1187 Switch from cordova-universal-links-plugin to cordova-universal-links…
  packages/auth/src/cordovahandler.js
  packages/auth/test/cordovahandler_test.js
Labels: Component-Auth

#1218 Consider JWTs with empty signatures to be valid
  packages/util/src/jwt.ts
Labels: needs-triage

#1223 change the build order, so declaration files are generated in the rig…
  packages/database/rollup.config.js
  packages/firestore/rollup.config.js
Labels: needs-triage

#1230 Upgrade closure-builder dependency to 2.3.0.
  packages/auth/package.json
  packages/webchannel-wrapper/package.json
  yarn.lock
Labels: Component-Core, needs-triage

#1231 add @Feiyang1 to the global code owners list
  .github/CODEOWNERS
Labels: needs-triage

#1233 Using SortedSet instead of a PriorityQueue
  packages/firestore/src/local/lru_garbage_collector.ts
Labels: needs-triage

#1224 Implement IndexedDB LRU Reference Delegate, add LRU tests
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/local/indexeddb_query_cache.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/lru_garbage_collector.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/simple_db.ts
  packages/firestore/test/unit/local/lru_garbage_collector.test.ts
Labels: needs-triage

#1236 Functions test fix
  packages/functions/test/browser/callable.test.ts
Labels: needs-triage

#1237 Implement LRU Reference Delegate for Memory Persistence
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/src/local/memory_persistence.ts
  packages/firestore/src/local/memory_query_cache.ts
  packages/firestore/src/local/memory_remote_document_cache.ts
  packages/firestore/src/local/persistence.ts
  packages/firestore/src/local/persistence_promise.ts
  packages/firestore/src/local/query_cache.ts
  packages/firestore/src/util/obj.ts
  packages/firestore/test/unit/local/lru_garbage_collector.test.ts
  packages/firestore/test/unit/local/persistence_test_helpers.ts
Labels: needs-triage

#1239 wrap component with try catch outside of iife for old browser compati…
  packages/firebase/rollup.config.js
Labels: needs-triage

#1247 Update test comments
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: needs-triage

#1248 support es6 module in webchannel-wrapper
  packages/webchannel-wrapper/package.json
  packages/webchannel-wrapper/tools/build.js
  yarn.lock
Labels: needs-triage

#1246 Remove computeInitialDocChanges
  packages/firestore/src/core/sync_engine.ts
  packages/firestore/src/core/view.ts
  packages/firestore/test/unit/core/event_manager.test.ts
Labels: Component-Firestore

#1253 Fix a few issues with the @firebase/testing package.json
  packages/testing/package.json
  packages/testing/src/api/index.ts
  packages/testing/test/database.test.ts
Labels: needs-triage

#1252 remove incorrect typing
  packages/firebase/index.d.ts
Labels: needs-triage

#1259 Add priming logic to integration tests to avoid backend cold start issues.
  packages/firestore/test/integration/prime_backend.test.ts
Labels: Component-Firestore
