Repository firebase/firebase-js-sdk, pull requests merged in 2019-01, with the labels that each got.

#1449 Allow both databaseName and projectId
  packages/testing/src/api/index.ts
Labels: needs-triage

#1443 Remove some Array to SortedSet<FieldPath> conversion
  packages/firestore/src/api/user_data_converter.ts
  packages/firestore/src/model/mutation.ts
Labels: needs-triage

#699 Remove unused Rollup plugins
  packages/app/package.json
  packages/app/rollup.config.js
  packages/database/package.json
  packages/database/rollup.config.js
  packages/firestore/package.json
  packages/firestore/rollup.config.js
  packages/functions/package.json
  packages/functions/rollup.config.js
  packages/logger/package.json
  packages/logger/rollup.config.js
  packages/messaging/package.json
  packages/messaging/rollup.config.js
  packages/polyfill/index.ts
  packages/polyfill/package.json
  packages/polyfill/rollup.config.js
  packages/storage/package.json
  packages/storage/rollup.config.js
  packages/template/package.json
  packages/template/rollup.config.js
  packages/testing/package.json
  packages/testing/rollup.config.js
  packages/util/package.json
  packages/util/rollup.config.js
Labels: Component-Core

#1454 Upgrade firestore emulator version to v1.2.3.
  scripts/emulator-testing/emulators/firestore-emulator.ts
Labels: needs-triage

#1438 Add code syntax highlighting
  packages/firebase/README.md
Labels: needs-triage

#1456 Treat ABORTED writes as retryable
  packages/firestore/src/remote/remote_store.ts
  packages/firestore/src/remote/rpc_error.ts
  packages/firestore/test/unit/specs/spec_builder.ts
  packages/firestore/test/unit/specs/write_spec.test.ts
Labels: Component-Firestore

#1458 use secret team as code owners to avoid review requests spam.
  .github/CODEOWNERS
  packages/testing/src/api/index.ts
Labels: needs-triage

#1462 Fixes #1450: ThenableReference should extend Promise, not PromiseLike.
  packages/database-types/index.d.ts
  packages/firebase/index.d.ts
Labels: Component-Database, needs-triage

#1347 Create empty-import.d.ts and reference it in submodule imports
  packages/firebase/auth/package.json
  packages/firebase/database/package.json
  packages/firebase/empty-import.d.ts
  packages/firebase/firestore/package.json
  packages/firebase/functions/package.json
  packages/firebase/messaging/package.json
  packages/rxfire/database/package.json
Labels: needs-triage

#1466 update grpc to 1.17.0
  packages/firestore/package.json
  packages/testing/package.json
  yarn.lock
Labels: needs-triage

#1465 Change downloaded emulator file mode to 'rwxr-xr-x'.
  scripts/emulator-testing/emulators/emulator.ts
Labels: needs-triage

#1470 Break import cycle
  packages/firestore/src/local/lru_garbage_collector.ts
Labels: Component-Firestore, needs-triage

#1473 Update to v1 protos.
  packages/firestore/src/platform_browser/webchannel_connection.ts
  packages/firestore/src/platform_node/grpc_connection.ts
  packages/firestore/src/platform_node/load_protos.ts
  packages/firestore/src/protos/firestore_proto_api.d.ts
  packages/firestore/src/protos/google/api/http.proto
  packages/firestore/src/protos/google/firestore/v1/common.proto
  packages/firestore/src/protos/google/firestore/v1/document.proto
  packages/firestore/src/protos/google/firestore/v1/firestore.proto
  packages/firestore/src/protos/google/firestore/v1/query.proto
  packages/firestore/src/protos/google/firestore/v1/write.proto
  packages/firestore/src/protos/google/protobuf/any.proto
  packages/firestore/src/protos/google/protobuf/timestamp.proto
  packages/firestore/src/protos/google/protobuf/wrappers.proto
  packages/firestore/src/protos/update.sh
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/integration/browser/webchannel.test.ts
  packages/firestore/test/unit/remote/node/serializer.test.ts
Labels: Component-Firestore, needs-triage

#1474 Add comment regarding presence of '/documents' to fromQueryPath().
  packages/firestore/src/remote/serializer.ts
Labels: Component-Firestore, needs-triage

#1464 Change timestampsInSnapshots default to true.
  packages/firebase/index.d.ts
  packages/firestore-types/index.d.ts
  packages/firestore/CHANGELOG.md
  packages/firestore/karma.conf.js
  packages/firestore/src/api/database.ts
  packages/firestore/src/model/field_value.ts
  packages/firestore/test/integration/api/fields.test.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/unit/model/field_value.test.ts
  packages/firestore/test/util/api_helpers.ts
  packages/rxfire/test/firestore.test.ts
  packages/testing/src/api/index.ts
Labels: Component-Firestore

#1476 Port "Stop persisting last acknowledged batch ID" from iOS
  packages/firestore/src/local/indexeddb_mutation_queue.ts
  packages/firestore/src/local/indexeddb_schema.ts
  packages/firestore/src/local/memory_mutation_queue.ts
  packages/firestore/test/unit/local/mutation_queue.test.ts
Labels: Component-Firestore

#1469 Consolidate mocha configurations into config file.
  config/karma.base.js
  config/mocha.base.js
  config/mocha.browser.opts
  config/mocha.node.opts
  packages/app/package.json
  packages/database/package.json
  packages/firestore/package.json
  packages/functions/package.json
  packages/logger/package.json
  packages/template/package.json
  packages/testing/package.json
  packages/util/package.json
Labels: needs-triage

#1479 Add @firebase/util dependencies to auth-types and storage-types
  packages/auth-types/package.json
  packages/storage-types/package.json
Labels: needs-triage

#1468 Do not print duplicate error messages to stdout.
  lerna.json
  package.json
  yarn.lock
Labels: needs-triage

#1453 Added firestoreClearData() testing sdk method
  packages/testing/index.ts
  packages/testing/src/api/index.ts
  packages/testing/test/database.test.ts
Labels: needs-triage

#1480 Prettier prepush improvements
  tools/gitHooks/prettier.js
Labels: needs-triage

#1484 Backport changelog fixups
  packages/firestore/CHANGELOG.md
Labels: needs-triage

#1483 update grpc to 1.18.0
  packages/firestore/package.json
  packages/testing/package.json
  yarn.lock
Labels: needs-triage

#1501 Verify large write batches support
  packages/firestore/test/integration/api/batch_writes.test.ts
Labels: Component-Firestore
