Repository firebase/firebase-js-sdk, pull requests merged in 2021-07, with the labels that each got.

#5127 [Auth] Fix broken public typings `d.ts` file
  common/api-review/auth-exp.api.md
  packages-exp/auth-exp/src/core/providers/email.ts
  packages-exp/auth-exp/src/core/providers/facebook.ts
  packages-exp/auth-exp/src/core/providers/github.ts
  packages-exp/auth-exp/src/core/providers/google.ts
  packages-exp/auth-exp/src/core/providers/twitter.ts
  packages-exp/auth-exp/src/model/id_token.ts
  packages-exp/auth-exp/src/platform_browser/providers/phone.ts
Labels: doc-changes, v9

#5128 Add cordova and react-native entry points to firebase/auth
  packages-exp/firebase-exp/auth/cordova/index.ts
  packages-exp/firebase-exp/auth/cordova/package.json
  packages-exp/firebase-exp/auth/react-native/index.ts
  packages-exp/firebase-exp/auth/react-native/package.json
  packages-exp/firebase-exp/package.json
Labels: v9

#5166 Skip IndexedDB cleanup on Safari 14
  .changeset/nine-needles-compare.md
  packages/firestore/src/local/indexeddb_persistence.ts
  packages/firestore/src/util/async_queue.ts
  packages/firestore/src/util/async_queue_impl.ts
  packages/firestore/test/unit/util/async_queue.test.ts
Labels: api: firestore

#5167 add esm entry points for node
  packages-exp/firebase-exp/analytics/package.json
  packages-exp/firebase-exp/app-check/package.json
  packages-exp/firebase-exp/app/package.json
  packages-exp/firebase-exp/auth/cordova/package.json
  packages-exp/firebase-exp/auth/package.json
  packages-exp/firebase-exp/auth/react-native/package.json
  packages-exp/firebase-exp/compat/analytics/package.json
  packages-exp/firebase-exp/compat/app-check/package.json
  packages-exp/firebase-exp/compat/app/package.json
  packages-exp/firebase-exp/compat/auth/package.json
  packages-exp/firebase-exp/compat/database/package.json
  packages-exp/firebase-exp/compat/firestore/package.json
  packages-exp/firebase-exp/compat/functions/package.json
  packages-exp/firebase-exp/compat/messaging/package.json
  packages-exp/firebase-exp/compat/package.json
  packages-exp/firebase-exp/compat/performance/package.json
  packages-exp/firebase-exp/compat/remote-config/package.json
  packages-exp/firebase-exp/compat/storage/package.json
  packages-exp/firebase-exp/database/package.json
  packages-exp/firebase-exp/firestore/lite/package.json
  packages-exp/firebase-exp/firestore/package.json
  packages-exp/firebase-exp/functions/package.json
  packages-exp/firebase-exp/messaging/package.json
  packages-exp/firebase-exp/messaging/sw/package.json
  packages-exp/firebase-exp/package.json
  packages-exp/firebase-exp/performance/package.json
  packages-exp/firebase-exp/remote-config/package.json
  packages-exp/firebase-exp/storage/package.json
Labels: v9

#5179 Rename all v9 modular useEmulator functions to connectEmulator
  common/api-review/auth-exp.api.md
  common/api-review/database.api.md
  common/api-review/functions-exp.api.md
  common/api-review/storage.api.md
  packages-exp/auth-compat-exp/src/auth.ts
  packages-exp/auth-exp/src/core/auth/emulator.test.ts
  packages-exp/auth-exp/src/core/auth/emulator.ts
  packages-exp/auth-exp/src/core/errors.ts
  packages-exp/auth-exp/src/core/index.ts
  packages-exp/auth-exp/test/helpers/integration/helpers.ts
  packages-exp/auth-exp/test/integration/webdriver/static/index.js
  packages-exp/functions-compat/src/service.test.ts
  packages-exp/functions-compat/src/service.ts
  packages-exp/functions-exp/src/api.ts
  packages-exp/functions-exp/src/service.test.ts
  packages-exp/functions-exp/src/service.ts
  packages-exp/functions-exp/test/utils.ts
  packages/database/exp/api.ts
  packages/database/src/api/Database.ts
  packages/database/src/exp/Database.ts
  packages/firestore/exp/api.ts
  packages/firestore/lite/index.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/exp/database.ts
  packages/firestore/src/lite/database.ts
  packages/storage/compat/service.ts
  packages/storage/exp/index.ts
  packages/storage/src/service.ts
  packages/storage/test/unit/service.compat.test.ts
  packages/storage/test/unit/service.exp.test.ts
Labels: doc-changes

#5136 Update database type names
  common/api-review/database-exp.api.md
  common/api-review/database.api.md
  packages-exp/app-check-exp/src/internal-api.ts
  packages/database/exp-types/index.d.ts
  packages/database/exp/api.ts
  packages/database/exp/register.ts
  packages/database/src/exp/Database.ts
  packages/database/src/exp/Reference.ts
  packages/database/src/exp/Reference_impl.ts
  packages/database/src/exp/Transaction.ts
Labels: doc-changes, v9

#5135 Update Firestore type names
  common/api-review/firestore-exp.api.md
  common/api-review/firestore-lite.api.md
  common/api-review/firestore.api.md
  packages/firestore/exp/api.ts
  packages/firestore/exp/register.ts
  packages/firestore/export.ts
  packages/firestore/index.console.ts
  packages/firestore/index.memory.ts
  packages/firestore/index.node.memory.ts
  packages/firestore/index.node.ts
  packages/firestore/index.rn.memory.ts
  packages/firestore/index.rn.ts
  packages/firestore/index.ts
  packages/firestore/lite/index.ts
  packages/firestore/lite/register.ts
  packages/firestore/package.json
  packages/firestore/src/api/database.ts
  packages/firestore/src/exp/database.ts
  packages/firestore/src/exp/reference_impl.ts
  packages/firestore/src/exp/settings.ts
  packages/firestore/src/exp/snapshot.ts
  packages/firestore/src/exp/transaction.ts
  packages/firestore/src/exp/write_batch.ts
  packages/firestore/src/lite/components.ts
  packages/firestore/src/lite/database.ts
  packages/firestore/src/lite/reference.ts
  packages/firestore/src/lite/reference_impl.ts
  packages/firestore/src/lite/settings.ts
  packages/firestore/src/lite/snapshot.ts
  packages/firestore/src/lite/transaction.ts
  packages/firestore/src/lite/user_data_reader.ts
  packages/firestore/src/lite/write_batch.ts
  packages/firestore/test/lite/helpers.ts
  packages/firestore/test/lite/integration.test.ts
  packages/firestore/test/util/api_helpers.ts
  repo-scripts/prune-dts/extract-public-api.ts
Labels: v9

#5182 [Auth] Add exported const map for error codes
  common/api-review/auth-exp.api.md
  packages-exp/auth-exp/src/core/errors.ts
  packages-exp/auth-exp/src/core/index.ts
Labels: doc-changes

#5206 Fix links and update event typings
  .changeset/wise-forks-poke.md
  packages-exp/analytics-exp/src/api.ts
  packages-exp/analytics-exp/src/public-types.ts
  packages-exp/firebase-exp/compat/index.d.ts
  packages/analytics-interop-types/index.d.ts
  packages/analytics-types/index.d.ts
  packages/firebase/index.d.ts
Labels: doc-changes

#5205 Fix transaction interference in v9
  packages/database/src/core/view/EventRegistration.ts
  packages/database/test/exp/integration.test.ts
  packages/database/test/transaction.test.ts
Labels: api: database, doc-changes
