Repository firebase/firebase-js-sdk, pull requests merged in 2021-09, with the labels that each got.

#5396 Fail more gracefully when opening IndexedDb fails in Firefox private browsing
  .changeset/brown-dog-twirl.md
  packages/firestore/src/local/simple_db.ts
Labels: api: firestore

#5285 Apply functional-style naming pattern to mutation.ts
  packages/firestore/src/local/local_documents_view.ts
  packages/firestore/src/local/local_store_impl.ts
  packages/firestore/src/model/mutation.ts
  packages/firestore/src/model/mutation_batch.ts
  packages/firestore/test/unit/model/mutation.test.ts
Labels: api: firestore

#5432 Add yarn build:debug
  packages/firestore/package.json
  packages/firestore/rollup.config.debug.js
Labels: api: firestore

#5452 Fix missing prefix in `signature` field in the public documentation
  packages/messaging/src/api.ts
  packages/messaging/src/index.sw.ts
Labels: doc-changes

#5455 Fix path typo in npm script
  packages/app-compat/package.json
Labels: doc-changes

#5434 Don't double-block AsyncQueue on auth token retrieval
  .changeset/cyan-eagles-carry.md
  packages/firestore/package.json
  packages/firestore/src/api/credentials.ts
  packages/firestore/test/integration/api_internal/auth.test.ts
Labels: api: firestore

#5453 Add protocol as a separate property for FirebaseStorage service
  .changeset/tender-pumpkins-love.md
  common/api-review/storage.api.md
  packages/storage/src/api.ts
  packages/storage/src/implementation/metadata.ts
  packages/storage/src/implementation/requests.ts
  packages/storage/src/implementation/url.ts
  packages/storage/src/service.ts
  packages/storage/test/unit/location.test.ts
  packages/storage/test/unit/requests.test.ts
  packages/storage/test/unit/service.test.ts
Labels: doc-changes

#5461 Temporary hack to fix terser output
  .changeset/spicy-moose-approve.md
  packages/firestore/rollup.shared.js
Labels: doc-changes

#5485 Remove backgroundChannelTest
  .changeset/shiny-rats-move.md
  packages/webchannel-wrapper/externs/overrides.js
Labels: api: firestore

#5493 Allow Firestore team to approve firestore-compat
  .github/CODEOWNERS
Labels: api: firestore

#5487 [Auth] Add phone factor ID to the PhoneMultiFactorGenerator object
  .changeset/neat-pants-wonder.md
  common/api-review/auth.api.md
  packages/auth/src/platform_browser/mfa/assertions/phone.ts
Labels: doc-changes

#5394 Support union types and optional fields with dot separation on UpdateData
  .changeset/clean-cameras-check.md
  common/api-review/firestore-lite.api.md
  common/api-review/firestore.api.md
  packages/firestore/lite/index.ts
  packages/firestore/src/api.ts
  packages/firestore/src/lite-api/reference.ts
  packages/firestore/src/lite-api/types.ts
  packages/firestore/test/lite/integration.test.ts
Labels: api: firestore, doc-changes

#3623 Add environment check to Remote-Config Module
  .changeset/blue-rice-ring.md
  common/api-review/remote-config.api.md
  packages/firebase/compat/index.d.ts
  packages/remote-config-compat/src/index.ts
  packages/remote-config-compat/src/remoteConfig.ts
  packages/remote-config/src/api2.ts
  packages/remote-config/src/errors.ts
  packages/remote-config/src/register.ts
  packages/remote-config/src/storage/storage.ts
Labels: api: remoteconfig, doc-changes

#5533 Export values from @firebase/database-compat
  packages/database-compat/src/index.ts
Labels: cla: yes

#5534 rename imports to avoid conflicts
  packages/database-compat/src/index.ts
Labels: cla: yes

#5535 trim all d.ts files in dist folder
  repo-scripts/prune-dts/tsconfig.eslint.json
  repo-scripts/prune-dts/tsconfig.json
Labels: cla: yes

#5512 Initialize App Check debug mode in initializeAppCheck
  packages/app-check/src/api.test.ts
  packages/app-check/src/api.ts
  packages/app-check/src/debug.ts
  packages/app-check/src/index.ts
  packages/app-check/src/state.ts
  packages/app-check/src/storage.ts
Labels: doc-changes

#5536 Ignore local projects in changeset
  .changeset/config.json
Labels: cla: yes

#5538 only publish dist to npm @firebase/firestore-compat
  .changeset/brown-ladybugs-invent.md
  packages/firestore-compat/package.json
Labels: cla: yes

#5540 Add changeset for #5512
  .changeset/clean-pens-invite.md
Labels: cla: yes

#5539 use esm2017 builds by default
  .changeset/heavy-books-mate.md
  .changeset/wet-queens-tell.md
  config/webpack.test.js
  packages/firestore/src/util/input_validation.ts
  packages/logger/package.json
  packages/logger/rollup.config.js
  packages/util/package.json
  packages/util/rollup.config.js
  packages/webchannel-wrapper/package.json
Labels: cla: yes

#5542 [Auth] Fix incorrectly-cased parameter in OOB request
  .changeset/swift-items-prove.md
  packages/auth/src/api/authentication/email_and_password.ts
  packages/auth/src/core/strategies/action_code_settings.ts
  packages/auth/src/core/strategies/email.test.ts
  packages/auth/src/core/strategies/email_and_password.test.ts
  packages/auth/src/core/strategies/email_link.test.ts
Labels: cla: yes

#5467 Misc source cleanup for Firebase Storage
  packages/storage/src/implementation/connection.ts
  packages/storage/src/implementation/error.ts
  packages/storage/src/implementation/request.ts
  packages/storage/src/implementation/requestinfo.ts
  packages/storage/src/platform/browser/connection.ts
  packages/storage/src/task.ts
  packages/storage/test/unit/connection.ts
  packages/storage/test/unit/string.test.ts
  packages/storage/test/unit/testshared.ts
Labels: api: storage

#5555 Fix changeset checker to stop using since option
  .github/workflows/check-changeset.yml
  .github/workflows/release.yml
  scripts/ci/check_changeset.ts
Labels: cla: yes

#5204 Add E2E workflow and tests
  .github/workflows/e2e-test.yml
  config/functions/index.js
  e2e/.gitignore
  e2e/README.md
  e2e/build/index.html
  e2e/context-template.html
  e2e/karma.conf.js
  e2e/package.json
  e2e/sample-apps/compat.js
  e2e/sample-apps/modular.js
  e2e/test-setup.js
  e2e/tests/compat.test.ts
  e2e/tests/modular.test.ts
  e2e/webpack.config.js
  e2e/yarn.lock
Labels: cla: yes

#5554 Use Authorization header instead of access_token for Github call
  repo-scripts/changelog-generator/index.ts
Labels: cla: yes

#5561 [Auth] Fix compat demo which was missing index.html file
  packages/auth-compat/demo/.gitignore
  packages/auth-compat/demo/package.json
  packages/auth-compat/demo/public/index.html
Labels: cla: yes

#5562 [Auth] Switch compat UserCredential function to use promise chaining instead of async/await
  .changeset/tame-owls-deny.md
  packages/auth-compat/src/user_credential.ts
Labels: cla: yes
