Repository firebase/firebase-js-sdk, pull requests merged in 2021-11, with the labels that each got.

#5689 [Auth] Add SAML provider to the compat layer
  .changeset/big-rocks-scream.md
  packages/auth-compat/index.ts
Labels: cla: yes

#5595 Implement ReCaptchaEnterprise for App Check
  .changeset/ten-impalas-wink.md
  common/api-review/app-check.api.md
  packages/app-check-compat/src/index.ts
  packages/app-check-compat/src/service.ts
  packages/app-check/src/api.test.ts
  packages/app-check/src/api.ts
  packages/app-check/src/client.test.ts
  packages/app-check/src/client.ts
  packages/app-check/src/constants.ts
  packages/app-check/src/internal-api.test.ts
  packages/app-check/src/providers.ts
  packages/app-check/src/public-types.ts
  packages/app-check/src/recaptcha.test.ts
  packages/app-check/src/recaptcha.ts
  packages/app-check/src/util.ts
  packages/app-check/test/util.ts
  packages/firebase/compat/index.d.ts
Labels: doc-changes, cla: yes

#5693 Add missing changset
  .changeset/proud-moose-taste.md
Labels: cla: yes

#5694 Add Rick to the global approver list
  .github/CODEOWNERS
Labels: cla: yes

#5675 Allow type T in WithFieldValue<T>
  .changeset/short-mice-itch.md
  common/api-review/firestore-lite.api.md
  common/api-review/firestore.api.md
  packages/firestore/src/lite-api/reference.ts
  packages/firestore/test/lite/integration.test.ts
Labels: doc-changes, cla: yes

#5698 Add regression tests to support primitive values in converters
  packages/firestore/test/lite/integration.test.ts
Labels: api: firestore, cla: yes

#5700 [Auth] Add tabindex=-1 to iframe to fix issue with aria-hidden
  .changeset/witty-kids-buy.md
  packages/auth/src/platform_browser/iframe/iframe.test.ts
  packages/auth/src/platform_browser/iframe/iframe.ts
Labels: cla: yes

#5708 Update build scripts to work with exports
  .changeset/spotty-ducks-buy.md
  packages/analytics-compat/package.json
  packages/analytics/package.json
  packages/app-check-compat/package.json
  packages/app-check/package.json
  packages/app-compat/package.json
  packages/app-compat/rollup.config.js
  packages/app/package.json
  packages/auth-compat/package.json
  packages/auth/package.json
  packages/component/package.json
  packages/database-compat/package.json
  packages/database-compat/rollup.config.js
  packages/database/package.json
  packages/firebase/compat/rollup.config.js
  packages/firestore-compat/package.json
  packages/firestore/package.json
  packages/functions-compat/package.json
  packages/functions/package.json
  packages/installations-compat/package.json
  packages/installations/package.json
  packages/logger/package.json
  packages/messaging-compat/package.json
  packages/messaging/package.json
  packages/performance-compat/package.json
  packages/performance/package.json
  packages/remote-config-compat/package.json
  packages/remote-config/package.json
  packages/storage-compat/package.json
  packages/storage/package.json
  packages/template/package.json
  packages/util/package.json
  packages/webchannel-wrapper/package.json
Labels: cla: yes

#5711 [Auth] Export getReactNativePersistence function
  packages/auth/index.rn.ts
  packages/auth/src/platform_react_native/persistence/react_native.ts
Labels: cla: yes

#5715 [Auth] Fix credentialFromResult docs
  .changeset/seven-glasses-worry.md
  packages/auth/src/core/providers/facebook.ts
  packages/auth/src/core/providers/github.ts
  packages/auth/src/core/providers/google.ts
  packages/auth/src/core/providers/twitter.ts
Labels: cla: yes

#5701 clear pending timeout after promise.race
  .changeset/cool-toys-marry.md
  packages/functions/src/service.ts
Labels: cla: yes

#5703 clear the global timeout once an operation is done in the Storage SDK
  .changeset/tame-beans-study.md
  packages/storage/src/implementation/backoff.ts
Labels: cla: yes

#5672 Add getBytes()
  .changeset/clever-eggs-relate.md
  common/api-review/storage.api.md
  packages/storage/.run/All Tests.run.xml
  packages/storage/src/api.browser.ts
  packages/storage/src/api.node.ts
  packages/storage/src/api.ts
  packages/storage/src/implementation/connection.ts
  packages/storage/src/implementation/request.ts
  packages/storage/src/implementation/requestinfo.ts
  packages/storage/src/implementation/requests.ts
  packages/storage/src/platform/browser/connection.ts
  packages/storage/src/platform/connection.ts
  packages/storage/src/platform/node/connection.ts
  packages/storage/src/reference.ts
  packages/storage/src/service.ts
  packages/storage/src/task.ts
  packages/storage/test/browser/blob.test.ts
  packages/storage/test/browser/connection.test.ts
  packages/storage/test/integration/integration.test.ts
  packages/storage/test/node/connection.test.ts
  packages/storage/test/node/stream.test.ts
  packages/storage/test/unit/connection.ts
  packages/storage/test/unit/request.test.ts
  packages/storage/test/unit/requests.test.ts
  packages/storage/test/unit/testshared.ts
Labels: api: storage, doc-changes, cla: yes

#5717 Skip IndexedDB cleanup on Safari 15
  .changeset/lovely-bobcats-punch.md
  packages/firestore/src/local/indexeddb_persistence.ts
Labels: cla: yes

#5725 Added instructions for running auth demo against emulator
  packages/auth/demo/README.md
  packages/auth/demo/package.json
  packages/auth/demo/src/index.js
Labels: cla: yes

#5727 [Auth] Update docs for UserCredential
  packages/auth/src/model/public_types.ts
Labels: cla: yes

#5706 Add bundle definitions and its measurement script.
  .github/workflows/health-metrics-test.yml
  repo-scripts/size-analysis/analyze-all-bundles.ts
  repo-scripts/size-analysis/bundle-analysis.ts
  repo-scripts/size-analysis/bundle-definition-examples/bundle-definition-1.json
  repo-scripts/size-analysis/bundle-definitions/analytics.json
  repo-scripts/size-analysis/bundle-definitions/app-check.json
  repo-scripts/size-analysis/bundle-definitions/auth.json
  repo-scripts/size-analysis/bundle-definitions/database.json
  repo-scripts/size-analysis/bundle-definitions/firestore-lite.json
  repo-scripts/size-analysis/bundle-definitions/firestore.json
  repo-scripts/size-analysis/bundle-definitions/functions.json
  repo-scripts/size-analysis/bundle-definitions/messaging.json
  repo-scripts/size-analysis/bundle-definitions/performance.json
  repo-scripts/size-analysis/bundle-definitions/remote-config.json
  repo-scripts/size-analysis/bundle-definitions/storage.json
  scripts/size_report/report_binary_size.ts
  scripts/size_report/size_report_helper.ts
Labels: cla: yes

#5602 Add GHA workflow for submitting tags to metric service.
  .github/workflows/health-metrics-pull-request.yml
  .github/workflows/health-metrics-release.yml
Labels: cla: yes

#5676 Add retry logic to app check
  .changeset/late-bottles-whisper.md
  packages/app-check/src/api.test.ts
  packages/app-check/src/api.ts
  packages/app-check/src/constants.ts
  packages/app-check/src/errors.ts
  packages/app-check/src/internal-api.test.ts
  packages/app-check/src/internal-api.ts
  packages/app-check/src/providers.test.ts
  packages/app-check/src/providers.ts
  packages/app-check/src/state.ts
  packages/app-check/src/types.ts
  packages/app-check/src/util.ts
Labels: cla: yes

#5738 better meta url polyfill
  .changeset/quick-experts-shave.md
  packages/firestore/rollup.config.js
Labels: cla: yes

#5743 Exclude NodeJS.ReadableStream from compat overloads
  .changeset/famous-houses-retire.md
  packages/storage/src/reference.ts
  scripts/build/create-overloads.ts
Labels: cla: yes

#5634 AppCheck integration for Firestore
  .changeset/mean-elephants-rush.md
  packages/firestore-compat/src/index.console.ts
  packages/firestore/externs.json
  packages/firestore/lite/register.ts
  packages/firestore/src/api.ts
  packages/firestore/src/api/credentials.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/component_provider.ts
  packages/firestore/src/core/firestore_client.ts
  packages/firestore/src/lite-api/components.ts
  packages/firestore/src/lite-api/database.ts
  packages/firestore/src/platform/browser/webchannel_connection.ts
  packages/firestore/src/platform/node/grpc_connection.ts
  packages/firestore/src/register.ts
  packages/firestore/src/remote/connection.ts
  packages/firestore/src/remote/datastore.ts
  packages/firestore/src/remote/persistent_stream.ts
  packages/firestore/src/remote/rest_connection.ts
  packages/firestore/test/integration/browser/webchannel.test.ts
  packages/firestore/test/integration/remote/stream.test.ts
  packages/firestore/test/integration/util/internal_helpers.ts
  packages/firestore/test/unit/api/database.test.ts
  packages/firestore/test/unit/remote/datastore.test.ts
  packages/firestore/test/unit/remote/rest_connection.test.ts
  packages/firestore/test/unit/specs/spec_test_components.ts
  packages/firestore/test/unit/specs/spec_test_runner.ts
  packages/firestore/test/util/api_helpers.ts
Labels: cla: yes

#5756 IntelliJ and VSCode runners for Babel
  .vscode/launch.json
  packages/firestore/.idea/runConfigurations/All_Tests__Emulator_.xml
  packages/firestore/.idea/runConfigurations/All_Tests__Emulator_w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests__Emulator_.xml
  packages/firestore/.idea/runConfigurations/Integration_Tests__Emulator_w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests.xml
  packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml
  packages/firestore/.idea/runConfigurations/firestore_lite_Tests__Emulator_.xml
  packages/firestore/babel.config.json
Labels: cla: yes

#5763 Fix caching errors during Firestore build
  packages/firestore/rollup.config.js
  packages/firestore/test/unit/specs/describe_spec.ts
Labels: api: firestore, cla: yes
