Repository firebase/firebase-js-sdk, pull requests merged in 2022-08, with the labels that each got.

#4773 Allow FirstPartyAuth to specify a token factory func.
  packages/firestore/src/api/credentials.ts
Labels: Status: Review Needed, needs-attention

#6510 Make index beta
  common/api-review/firestore.api.md
  packages/firestore/src/api/index_configuration.ts
Labels: doc-changes

#6518 Tomandersen/multi db
  .changeset/heavy-spiders-fry.md
  common/api-review/firestore-lite.api.md
  common/api-review/firestore.api.md
  integration/firestore/firebase_export.ts
  packages/firestore-compat/src/index.console.ts
  packages/firestore/lite/register.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/database_info.ts
  packages/firestore/src/lite-api/database.ts
  packages/firestore/src/register.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/provider.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/util/firebase_export.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/lite/integration.test.ts
  packages/firestore/test/util/api_helpers.ts
Labels: doc-changes

#6528 Mila/count implement count query
  common/api-review/firestore.api.md
  packages/firestore/src/lite-api/aggregate.ts
  packages/firestore/src/protos/firestore_proto_api.ts
  packages/firestore/src/remote/datastore.ts
  packages/firestore/src/remote/rest_connection.ts
  packages/firestore/src/remote/serializer.ts
  packages/firestore/test/integration/api/count.test.ts
  packages/firestore/test/lite/integration.test.ts
Labels: doc-changes

#6554 Revert "Revert "Tomandersen/multi db"" -- and make api internal
  common/api-review/firestore-lite.api.md
  common/api-review/firestore.api.md
  integration/firestore/firebase_export.ts
  packages/firestore-compat/src/index.console.ts
  packages/firestore/lite/register.ts
  packages/firestore/src/api/database.ts
  packages/firestore/src/core/database_info.ts
  packages/firestore/src/lite-api/database.ts
  packages/firestore/src/register.ts
  packages/firestore/test/integration/api/database.test.ts
  packages/firestore/test/integration/api/provider.test.ts
  packages/firestore/test/integration/api/validation.test.ts
  packages/firestore/test/integration/util/firebase_export.ts
  packages/firestore/test/integration/util/helpers.ts
  packages/firestore/test/lite/integration.test.ts
  packages/firestore/test/util/api_helpers.ts
Labels: doc-changes

#6550 Firestore: Fix FAILED_PRECONDITION when writing to a deleted document in a transaction
  .changeset/smart-plants-sparkle.md
  packages/firestore/src/core/transaction.ts
  packages/firestore/test/integration/api/transactions.test.ts
  packages/firestore/test/lite/integration.test.ts
Labels: api: firestore
